/*
 * FEVER Retrieval
 *
 * The multimodal media database. Images, video, audio, office documents, and LiDAR in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans, collection grouping, and asset-to-asset attachments. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.4.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using LowdownLabs.Fever.Client;
using LowdownLabs.Fever.Api;
// uncomment below to import models
//using LowdownLabs.Fever.Model;

namespace LowdownLabs.Fever.Test.Api
{
    /// <summary>
    ///  Class for testing IngestApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class IngestApiTests : IDisposable
    {
        private IngestApi instance;

        public IngestApiTests()
        {
            instance = new IngestApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IngestApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' IngestApi
            //Assert.IsType<IngestApi>(instance);
        }

        /// <summary>
        /// Test IngestMedia
        /// </summary>
        [Fact]
        public void IngestMediaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //IngestRequest ingestRequest = null;
            //var response = instance.IngestMedia(ingestRequest);
            //Assert.IsType<IngestResult>(response);
        }
    }
}
