/*
 * FEVER Retrieval
 *
 * The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using LowdownLabs.Fever.Client;
using LowdownLabs.Fever.Model;

namespace LowdownLabs.Fever.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IKeysApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Mint an API key for this appliance
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createKeyRequest"></param>
        /// <param name="authorization"> (optional)</param>
        /// <returns>KeyReveal</returns>
        KeyReveal CreateKey(CreateKeyRequest createKeyRequest, string? authorization = default);

        /// <summary>
        /// Mint an API key for this appliance
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createKeyRequest"></param>
        /// <param name="authorization"> (optional)</param>
        /// <returns>ApiResponse of KeyReveal</returns>
        ApiResponse<KeyReveal> CreateKeyWithHttpInfo(CreateKeyRequest createKeyRequest, string? authorization = default);
        /// <summary>
        /// List this appliance&#39;s API keys
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization"> (optional)</param>
        /// <returns>List&lt;ApiKey&gt;</returns>
        List<ApiKey> ListKeys(string? authorization = default);

        /// <summary>
        /// List this appliance&#39;s API keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization"> (optional)</param>
        /// <returns>ApiResponse of List&lt;ApiKey&gt;</returns>
        ApiResponse<List<ApiKey>> ListKeysWithHttpInfo(string? authorization = default);
        /// <summary>
        /// Revoke an API key
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"></param>
        /// <param name="authorization"> (optional)</param>
        /// <returns>Object</returns>
        Object RevokeKey(int keyId, string? authorization = default);

        /// <summary>
        /// Revoke an API key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"></param>
        /// <param name="authorization"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> RevokeKeyWithHttpInfo(int keyId, string? authorization = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IKeysApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Mint an API key for this appliance
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createKeyRequest"></param>
        /// <param name="authorization"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of KeyReveal</returns>
        System.Threading.Tasks.Task<KeyReveal> CreateKeyAsync(CreateKeyRequest createKeyRequest, string? authorization = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Mint an API key for this appliance
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createKeyRequest"></param>
        /// <param name="authorization"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (KeyReveal)</returns>
        System.Threading.Tasks.Task<ApiResponse<KeyReveal>> CreateKeyWithHttpInfoAsync(CreateKeyRequest createKeyRequest, string? authorization = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List this appliance&#39;s API keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ApiKey&gt;</returns>
        System.Threading.Tasks.Task<List<ApiKey>> ListKeysAsync(string? authorization = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List this appliance&#39;s API keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ApiKey&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ApiKey>>> ListKeysWithHttpInfoAsync(string? authorization = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Revoke an API key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"></param>
        /// <param name="authorization"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> RevokeKeyAsync(int keyId, string? authorization = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Revoke an API key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"></param>
        /// <param name="authorization"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RevokeKeyWithHttpInfoAsync(int keyId, string? authorization = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IKeysApi : IKeysApiSync, IKeysApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class KeysApi : IDisposable, IKeysApi
    {
        private LowdownLabs.Fever.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="KeysApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public KeysApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="KeysApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public KeysApi(string basePath)
        {
            this.Configuration = LowdownLabs.Fever.Client.Configuration.MergeConfigurations(
                LowdownLabs.Fever.Client.GlobalConfiguration.Instance,
                new LowdownLabs.Fever.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new LowdownLabs.Fever.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = LowdownLabs.Fever.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="KeysApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public KeysApi(LowdownLabs.Fever.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = LowdownLabs.Fever.Client.Configuration.MergeConfigurations(
                LowdownLabs.Fever.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new LowdownLabs.Fever.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = LowdownLabs.Fever.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="KeysApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public KeysApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="KeysApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public KeysApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = LowdownLabs.Fever.Client.Configuration.MergeConfigurations(
                LowdownLabs.Fever.Client.GlobalConfiguration.Instance,
                new LowdownLabs.Fever.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new LowdownLabs.Fever.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = LowdownLabs.Fever.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="KeysApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public KeysApi(HttpClient client, LowdownLabs.Fever.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = LowdownLabs.Fever.Client.Configuration.MergeConfigurations(
                LowdownLabs.Fever.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new LowdownLabs.Fever.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = LowdownLabs.Fever.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="KeysApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public KeysApi(LowdownLabs.Fever.Client.ISynchronousClient client, LowdownLabs.Fever.Client.IAsynchronousClient asyncClient, LowdownLabs.Fever.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = LowdownLabs.Fever.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public LowdownLabs.Fever.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public LowdownLabs.Fever.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public LowdownLabs.Fever.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public LowdownLabs.Fever.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public LowdownLabs.Fever.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Mint an API key for this appliance 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createKeyRequest"></param>
        /// <param name="authorization"> (optional)</param>
        /// <returns>KeyReveal</returns>
        public KeyReveal CreateKey(CreateKeyRequest createKeyRequest, string? authorization = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<KeyReveal> localVarResponse = CreateKeyWithHttpInfo(createKeyRequest, authorization);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Mint an API key for this appliance 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createKeyRequest"></param>
        /// <param name="authorization"> (optional)</param>
        /// <returns>ApiResponse of KeyReveal</returns>
        public LowdownLabs.Fever.Client.ApiResponse<KeyReveal> CreateKeyWithHttpInfo(CreateKeyRequest createKeyRequest, string? authorization = default)
        {
            // verify the required parameter 'createKeyRequest' is set
            if (createKeyRequest == null)
                throw new LowdownLabs.Fever.Client.ApiException(400, "Missing required parameter 'createKeyRequest' when calling KeysApi->CreateKey");

            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (authorization != null)
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(authorization)); // header parameter
            }
            localVarRequestOptions.Data = createKeyRequest;


            // make the HTTP request
            var localVarResponse = this.Client.Post<KeyReveal>("/v1/keys", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateKey", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Mint an API key for this appliance 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createKeyRequest"></param>
        /// <param name="authorization"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of KeyReveal</returns>
        public async System.Threading.Tasks.Task<KeyReveal> CreateKeyAsync(CreateKeyRequest createKeyRequest, string? authorization = default, System.Threading.CancellationToken cancellationToken = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<KeyReveal> localVarResponse = await CreateKeyWithHttpInfoAsync(createKeyRequest, authorization, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Mint an API key for this appliance 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createKeyRequest"></param>
        /// <param name="authorization"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (KeyReveal)</returns>
        public async System.Threading.Tasks.Task<LowdownLabs.Fever.Client.ApiResponse<KeyReveal>> CreateKeyWithHttpInfoAsync(CreateKeyRequest createKeyRequest, string? authorization = default, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createKeyRequest' is set
            if (createKeyRequest == null)
                throw new LowdownLabs.Fever.Client.ApiException(400, "Missing required parameter 'createKeyRequest' when calling KeysApi->CreateKey");


            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (authorization != null)
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(authorization)); // header parameter
            }
            localVarRequestOptions.Data = createKeyRequest;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<KeyReveal>("/v1/keys", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateKey", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List this appliance&#39;s API keys 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization"> (optional)</param>
        /// <returns>List&lt;ApiKey&gt;</returns>
        public List<ApiKey> ListKeys(string? authorization = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<List<ApiKey>> localVarResponse = ListKeysWithHttpInfo(authorization);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List this appliance&#39;s API keys 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization"> (optional)</param>
        /// <returns>ApiResponse of List&lt;ApiKey&gt;</returns>
        public LowdownLabs.Fever.Client.ApiResponse<List<ApiKey>> ListKeysWithHttpInfo(string? authorization = default)
        {
            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (authorization != null)
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(authorization)); // header parameter
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<ApiKey>>("/v1/keys", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListKeys", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List this appliance&#39;s API keys 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ApiKey&gt;</returns>
        public async System.Threading.Tasks.Task<List<ApiKey>> ListKeysAsync(string? authorization = default, System.Threading.CancellationToken cancellationToken = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<List<ApiKey>> localVarResponse = await ListKeysWithHttpInfoAsync(authorization, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List this appliance&#39;s API keys 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ApiKey&gt;)</returns>
        public async System.Threading.Tasks.Task<LowdownLabs.Fever.Client.ApiResponse<List<ApiKey>>> ListKeysWithHttpInfoAsync(string? authorization = default, System.Threading.CancellationToken cancellationToken = default)
        {

            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (authorization != null)
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(authorization)); // header parameter
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<ApiKey>>("/v1/keys", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListKeys", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revoke an API key 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"></param>
        /// <param name="authorization"> (optional)</param>
        /// <returns>Object</returns>
        public Object RevokeKey(int keyId, string? authorization = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<Object> localVarResponse = RevokeKeyWithHttpInfo(keyId, authorization);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Revoke an API key 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"></param>
        /// <param name="authorization"> (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public LowdownLabs.Fever.Client.ApiResponse<Object> RevokeKeyWithHttpInfo(int keyId, string? authorization = default)
        {
            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("key_id", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(keyId)); // path parameter
            if (authorization != null)
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(authorization)); // header parameter
            }


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/v1/keys/{key_id}/revoke", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RevokeKey", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revoke an API key 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"></param>
        /// <param name="authorization"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> RevokeKeyAsync(int keyId, string? authorization = default, System.Threading.CancellationToken cancellationToken = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<Object> localVarResponse = await RevokeKeyWithHttpInfoAsync(keyId, authorization, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Revoke an API key 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"></param>
        /// <param name="authorization"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<LowdownLabs.Fever.Client.ApiResponse<Object>> RevokeKeyWithHttpInfoAsync(int keyId, string? authorization = default, System.Threading.CancellationToken cancellationToken = default)
        {

            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("key_id", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(keyId)); // path parameter
            if (authorization != null)
            {
                localVarRequestOptions.HeaderParameters.Add("authorization", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(authorization)); // header parameter
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/v1/keys/{key_id}/revoke", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RevokeKey", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
