/*
 * FEVER Retrieval
 *
 * The multimodal media database. Images, video, audio, office documents, and LiDAR in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans, collection grouping, and asset-to-asset attachments. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.4.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using LowdownLabs.Fever.Client;
using LowdownLabs.Fever.Model;

namespace LowdownLabs.Fever.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMediaApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Set a blob&#39;s collection and/or parent association (e.g. attach a LiDAR scan to its source photo)
        /// </summary>
        /// <remarks>
        /// Fill the relational columns after ingest (the SOR-driven import flow): collection_id groups assets under a client-owned project; parent_ref ties a companion asset (LiDAR, transcript, alternate capture) to its parent. Values are COALESCE-updates - present fields win, omitted fields stay. Re-ingesting the same content with the fields set does the same thing through the upsert.
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="associateRequest"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>MediaInfo</returns>
        MediaInfo AssociateMedia(int blobId, AssociateRequest associateRequest, string? customerId = default);

        /// <summary>
        /// Set a blob&#39;s collection and/or parent association (e.g. attach a LiDAR scan to its source photo)
        /// </summary>
        /// <remarks>
        /// Fill the relational columns after ingest (the SOR-driven import flow): collection_id groups assets under a client-owned project; parent_ref ties a companion asset (LiDAR, transcript, alternate capture) to its parent. Values are COALESCE-updates - present fields win, omitted fields stay. Re-ingesting the same content with the fields set does the same thing through the upsert.
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="associateRequest"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>ApiResponse of MediaInfo</returns>
        ApiResponse<MediaInfo> AssociateMediaWithHttpInfo(int blobId, AssociateRequest associateRequest, string? customerId = default);
        /// <summary>
        /// Fetch an indexed media item&#39;s bytes (images normalized to JPEG)
        /// </summary>
        /// <remarks>
        /// Return the bytes for a blob_id (JPEG, normalized to max_dim; 0 &#x3D; raw bytes). Scoped keys can only fetch their own customer&#39;s items; other customers&#39; blobs are a 404 (never an existence leak).  ?waveform&#x3D;1 renders an audio blob&#39;s waveform as a PNG (ffmpeg showwavespic) so clients can show a real visual for audio hits without decoding the clip in the browser.
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="maxDim"> (optional, default to 1280)</param>
        /// <param name="waveform"> (optional, default to 0)</param>
        /// <returns>Object</returns>
        Object GetMediaBytes(int blobId, int? maxDim = default, int? waveform = default);

        /// <summary>
        /// Fetch an indexed media item&#39;s bytes (images normalized to JPEG)
        /// </summary>
        /// <remarks>
        /// Return the bytes for a blob_id (JPEG, normalized to max_dim; 0 &#x3D; raw bytes). Scoped keys can only fetch their own customer&#39;s items; other customers&#39; blobs are a 404 (never an existence leak).  ?waveform&#x3D;1 renders an audio blob&#39;s waveform as a PNG (ffmpeg showwavespic) so clients can show a real visual for audio hits without decoding the clip in the browser.
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="maxDim"> (optional, default to 1280)</param>
        /// <param name="waveform"> (optional, default to 0)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> GetMediaBytesWithHttpInfo(int blobId, int? maxDim = default, int? waveform = default);
        /// <summary>
        /// Everything known about a blob: annotations, EXIF summary, media kind, derived artifact counts
        /// </summary>
        /// <remarks>
        /// Unified record for a blob_id. Scoped keys can only read their own customer&#39;s blobs; other customers&#39; blobs are a 404 (never an existence leak). Admin keys may narrow with ?customer_id&#x3D;.
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>MediaInfo</returns>
        MediaInfo GetMediaInfo(int blobId, string? customerId = default);

        /// <summary>
        /// Everything known about a blob: annotations, EXIF summary, media kind, derived artifact counts
        /// </summary>
        /// <remarks>
        /// Unified record for a blob_id. Scoped keys can only read their own customer&#39;s blobs; other customers&#39; blobs are a 404 (never an existence leak). Admin keys may narrow with ?customer_id&#x3D;.
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>ApiResponse of MediaInfo</returns>
        ApiResponse<MediaInfo> GetMediaInfoWithHttpInfo(int blobId, string? customerId = default);
        /// <summary>
        /// Ingest capability: supported extensions per media family
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>MediaFormats</returns>
        MediaFormats ListMediaFormats();

        /// <summary>
        /// Ingest capability: supported extensions per media family
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of MediaFormats</returns>
        ApiResponse<MediaFormats> ListMediaFormatsWithHttpInfo();
        /// <summary>
        /// Sampled video frames for a parent blob
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>List&lt;MediaFrame&gt;</returns>
        List<MediaFrame> ListMediaFrames(int blobId, string? customerId = default);

        /// <summary>
        /// Sampled video frames for a parent blob
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>ApiResponse of List&lt;MediaFrame&gt;</returns>
        ApiResponse<List<MediaFrame>> ListMediaFramesWithHttpInfo(int blobId, string? customerId = default);
        /// <summary>
        /// Whisper transcript segments for a parent blob (audio or video)
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>List&lt;TranscriptSegment&gt;</returns>
        List<TranscriptSegment> ListMediaTranscript(int blobId, string? customerId = default);

        /// <summary>
        /// Whisper transcript segments for a parent blob (audio or video)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>ApiResponse of List&lt;TranscriptSegment&gt;</returns>
        ApiResponse<List<TranscriptSegment>> ListMediaTranscriptWithHttpInfo(int blobId, string? customerId = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMediaApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Set a blob&#39;s collection and/or parent association (e.g. attach a LiDAR scan to its source photo)
        /// </summary>
        /// <remarks>
        /// Fill the relational columns after ingest (the SOR-driven import flow): collection_id groups assets under a client-owned project; parent_ref ties a companion asset (LiDAR, transcript, alternate capture) to its parent. Values are COALESCE-updates - present fields win, omitted fields stay. Re-ingesting the same content with the fields set does the same thing through the upsert.
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="associateRequest"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MediaInfo</returns>
        System.Threading.Tasks.Task<MediaInfo> AssociateMediaAsync(int blobId, AssociateRequest associateRequest, string? customerId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Set a blob&#39;s collection and/or parent association (e.g. attach a LiDAR scan to its source photo)
        /// </summary>
        /// <remarks>
        /// Fill the relational columns after ingest (the SOR-driven import flow): collection_id groups assets under a client-owned project; parent_ref ties a companion asset (LiDAR, transcript, alternate capture) to its parent. Values are COALESCE-updates - present fields win, omitted fields stay. Re-ingesting the same content with the fields set does the same thing through the upsert.
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="associateRequest"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MediaInfo)</returns>
        System.Threading.Tasks.Task<ApiResponse<MediaInfo>> AssociateMediaWithHttpInfoAsync(int blobId, AssociateRequest associateRequest, string? customerId = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Fetch an indexed media item&#39;s bytes (images normalized to JPEG)
        /// </summary>
        /// <remarks>
        /// Return the bytes for a blob_id (JPEG, normalized to max_dim; 0 &#x3D; raw bytes). Scoped keys can only fetch their own customer&#39;s items; other customers&#39; blobs are a 404 (never an existence leak).  ?waveform&#x3D;1 renders an audio blob&#39;s waveform as a PNG (ffmpeg showwavespic) so clients can show a real visual for audio hits without decoding the clip in the browser.
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="maxDim"> (optional, default to 1280)</param>
        /// <param name="waveform"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> GetMediaBytesAsync(int blobId, int? maxDim = default, int? waveform = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Fetch an indexed media item&#39;s bytes (images normalized to JPEG)
        /// </summary>
        /// <remarks>
        /// Return the bytes for a blob_id (JPEG, normalized to max_dim; 0 &#x3D; raw bytes). Scoped keys can only fetch their own customer&#39;s items; other customers&#39; blobs are a 404 (never an existence leak).  ?waveform&#x3D;1 renders an audio blob&#39;s waveform as a PNG (ffmpeg showwavespic) so clients can show a real visual for audio hits without decoding the clip in the browser.
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="maxDim"> (optional, default to 1280)</param>
        /// <param name="waveform"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GetMediaBytesWithHttpInfoAsync(int blobId, int? maxDim = default, int? waveform = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Everything known about a blob: annotations, EXIF summary, media kind, derived artifact counts
        /// </summary>
        /// <remarks>
        /// Unified record for a blob_id. Scoped keys can only read their own customer&#39;s blobs; other customers&#39; blobs are a 404 (never an existence leak). Admin keys may narrow with ?customer_id&#x3D;.
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MediaInfo</returns>
        System.Threading.Tasks.Task<MediaInfo> GetMediaInfoAsync(int blobId, string? customerId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Everything known about a blob: annotations, EXIF summary, media kind, derived artifact counts
        /// </summary>
        /// <remarks>
        /// Unified record for a blob_id. Scoped keys can only read their own customer&#39;s blobs; other customers&#39; blobs are a 404 (never an existence leak). Admin keys may narrow with ?customer_id&#x3D;.
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MediaInfo)</returns>
        System.Threading.Tasks.Task<ApiResponse<MediaInfo>> GetMediaInfoWithHttpInfoAsync(int blobId, string? customerId = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Ingest capability: supported extensions per media family
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MediaFormats</returns>
        System.Threading.Tasks.Task<MediaFormats> ListMediaFormatsAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Ingest capability: supported extensions per media family
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MediaFormats)</returns>
        System.Threading.Tasks.Task<ApiResponse<MediaFormats>> ListMediaFormatsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Sampled video frames for a parent blob
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;MediaFrame&gt;</returns>
        System.Threading.Tasks.Task<List<MediaFrame>> ListMediaFramesAsync(int blobId, string? customerId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Sampled video frames for a parent blob
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;MediaFrame&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<MediaFrame>>> ListMediaFramesWithHttpInfoAsync(int blobId, string? customerId = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Whisper transcript segments for a parent blob (audio or video)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;TranscriptSegment&gt;</returns>
        System.Threading.Tasks.Task<List<TranscriptSegment>> ListMediaTranscriptAsync(int blobId, string? customerId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Whisper transcript segments for a parent blob (audio or video)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;TranscriptSegment&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<TranscriptSegment>>> ListMediaTranscriptWithHttpInfoAsync(int blobId, string? customerId = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMediaApi : IMediaApiSync, IMediaApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MediaApi : IDisposable, IMediaApi
    {
        private LowdownLabs.Fever.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public MediaApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public MediaApi(string basePath)
        {
            this.Configuration = LowdownLabs.Fever.Client.Configuration.MergeConfigurations(
                LowdownLabs.Fever.Client.GlobalConfiguration.Instance,
                new LowdownLabs.Fever.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new LowdownLabs.Fever.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = LowdownLabs.Fever.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public MediaApi(LowdownLabs.Fever.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = LowdownLabs.Fever.Client.Configuration.MergeConfigurations(
                LowdownLabs.Fever.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new LowdownLabs.Fever.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = LowdownLabs.Fever.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MediaApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MediaApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = LowdownLabs.Fever.Client.Configuration.MergeConfigurations(
                LowdownLabs.Fever.Client.GlobalConfiguration.Instance,
                new LowdownLabs.Fever.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new LowdownLabs.Fever.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = LowdownLabs.Fever.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MediaApi(HttpClient client, LowdownLabs.Fever.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = LowdownLabs.Fever.Client.Configuration.MergeConfigurations(
                LowdownLabs.Fever.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new LowdownLabs.Fever.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = LowdownLabs.Fever.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public MediaApi(LowdownLabs.Fever.Client.ISynchronousClient client, LowdownLabs.Fever.Client.IAsynchronousClient asyncClient, LowdownLabs.Fever.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = LowdownLabs.Fever.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public LowdownLabs.Fever.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public LowdownLabs.Fever.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public LowdownLabs.Fever.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public LowdownLabs.Fever.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public LowdownLabs.Fever.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Set a blob&#39;s collection and/or parent association (e.g. attach a LiDAR scan to its source photo) Fill the relational columns after ingest (the SOR-driven import flow): collection_id groups assets under a client-owned project; parent_ref ties a companion asset (LiDAR, transcript, alternate capture) to its parent. Values are COALESCE-updates - present fields win, omitted fields stay. Re-ingesting the same content with the fields set does the same thing through the upsert.
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="associateRequest"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>MediaInfo</returns>
        public MediaInfo AssociateMedia(int blobId, AssociateRequest associateRequest, string? customerId = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<MediaInfo> localVarResponse = AssociateMediaWithHttpInfo(blobId, associateRequest, customerId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Set a blob&#39;s collection and/or parent association (e.g. attach a LiDAR scan to its source photo) Fill the relational columns after ingest (the SOR-driven import flow): collection_id groups assets under a client-owned project; parent_ref ties a companion asset (LiDAR, transcript, alternate capture) to its parent. Values are COALESCE-updates - present fields win, omitted fields stay. Re-ingesting the same content with the fields set does the same thing through the upsert.
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="associateRequest"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>ApiResponse of MediaInfo</returns>
        public LowdownLabs.Fever.Client.ApiResponse<MediaInfo> AssociateMediaWithHttpInfo(int blobId, AssociateRequest associateRequest, string? customerId = default)
        {
            // verify the required parameter 'associateRequest' is set
            if (associateRequest == null)
                throw new LowdownLabs.Fever.Client.ApiException(400, "Missing required parameter 'associateRequest' when calling MediaApi->AssociateMedia");

            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("blob_id", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(blobId)); // path parameter
            if (customerId != null)
            {
                localVarRequestOptions.QueryParameters.Add(LowdownLabs.Fever.Client.ClientUtils.ParameterToMultiMap("", "customer_id", customerId));
            }
            localVarRequestOptions.Data = associateRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<MediaInfo>("/v1/media/{blob_id}/associate", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AssociateMedia", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Set a blob&#39;s collection and/or parent association (e.g. attach a LiDAR scan to its source photo) Fill the relational columns after ingest (the SOR-driven import flow): collection_id groups assets under a client-owned project; parent_ref ties a companion asset (LiDAR, transcript, alternate capture) to its parent. Values are COALESCE-updates - present fields win, omitted fields stay. Re-ingesting the same content with the fields set does the same thing through the upsert.
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="associateRequest"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MediaInfo</returns>
        public async System.Threading.Tasks.Task<MediaInfo> AssociateMediaAsync(int blobId, AssociateRequest associateRequest, string? customerId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<MediaInfo> localVarResponse = await AssociateMediaWithHttpInfoAsync(blobId, associateRequest, customerId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Set a blob&#39;s collection and/or parent association (e.g. attach a LiDAR scan to its source photo) Fill the relational columns after ingest (the SOR-driven import flow): collection_id groups assets under a client-owned project; parent_ref ties a companion asset (LiDAR, transcript, alternate capture) to its parent. Values are COALESCE-updates - present fields win, omitted fields stay. Re-ingesting the same content with the fields set does the same thing through the upsert.
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="associateRequest"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MediaInfo)</returns>
        public async System.Threading.Tasks.Task<LowdownLabs.Fever.Client.ApiResponse<MediaInfo>> AssociateMediaWithHttpInfoAsync(int blobId, AssociateRequest associateRequest, string? customerId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'associateRequest' is set
            if (associateRequest == null)
                throw new LowdownLabs.Fever.Client.ApiException(400, "Missing required parameter 'associateRequest' when calling MediaApi->AssociateMedia");


            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("blob_id", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(blobId)); // path parameter
            if (customerId != null)
            {
                localVarRequestOptions.QueryParameters.Add(LowdownLabs.Fever.Client.ClientUtils.ParameterToMultiMap("", "customer_id", customerId));
            }
            localVarRequestOptions.Data = associateRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<MediaInfo>("/v1/media/{blob_id}/associate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AssociateMedia", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fetch an indexed media item&#39;s bytes (images normalized to JPEG) Return the bytes for a blob_id (JPEG, normalized to max_dim; 0 &#x3D; raw bytes). Scoped keys can only fetch their own customer&#39;s items; other customers&#39; blobs are a 404 (never an existence leak).  ?waveform&#x3D;1 renders an audio blob&#39;s waveform as a PNG (ffmpeg showwavespic) so clients can show a real visual for audio hits without decoding the clip in the browser.
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="maxDim"> (optional, default to 1280)</param>
        /// <param name="waveform"> (optional, default to 0)</param>
        /// <returns>Object</returns>
        public Object GetMediaBytes(int blobId, int? maxDim = default, int? waveform = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<Object> localVarResponse = GetMediaBytesWithHttpInfo(blobId, maxDim, waveform);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetch an indexed media item&#39;s bytes (images normalized to JPEG) Return the bytes for a blob_id (JPEG, normalized to max_dim; 0 &#x3D; raw bytes). Scoped keys can only fetch their own customer&#39;s items; other customers&#39; blobs are a 404 (never an existence leak).  ?waveform&#x3D;1 renders an audio blob&#39;s waveform as a PNG (ffmpeg showwavespic) so clients can show a real visual for audio hits without decoding the clip in the browser.
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="maxDim"> (optional, default to 1280)</param>
        /// <param name="waveform"> (optional, default to 0)</param>
        /// <returns>ApiResponse of Object</returns>
        public LowdownLabs.Fever.Client.ApiResponse<Object> GetMediaBytesWithHttpInfo(int blobId, int? maxDim = default, int? waveform = default)
        {
            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "image/jpeg",
                "image/png"
            };

            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("blob_id", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(blobId)); // path parameter
            if (maxDim != null)
            {
                localVarRequestOptions.QueryParameters.Add(LowdownLabs.Fever.Client.ClientUtils.ParameterToMultiMap("", "max_dim", maxDim));
            }
            if (waveform != null)
            {
                localVarRequestOptions.QueryParameters.Add(LowdownLabs.Fever.Client.ClientUtils.ParameterToMultiMap("", "waveform", waveform));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/media/{blob_id}/bytes", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMediaBytes", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fetch an indexed media item&#39;s bytes (images normalized to JPEG) Return the bytes for a blob_id (JPEG, normalized to max_dim; 0 &#x3D; raw bytes). Scoped keys can only fetch their own customer&#39;s items; other customers&#39; blobs are a 404 (never an existence leak).  ?waveform&#x3D;1 renders an audio blob&#39;s waveform as a PNG (ffmpeg showwavespic) so clients can show a real visual for audio hits without decoding the clip in the browser.
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="maxDim"> (optional, default to 1280)</param>
        /// <param name="waveform"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> GetMediaBytesAsync(int blobId, int? maxDim = default, int? waveform = default, System.Threading.CancellationToken cancellationToken = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<Object> localVarResponse = await GetMediaBytesWithHttpInfoAsync(blobId, maxDim, waveform, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetch an indexed media item&#39;s bytes (images normalized to JPEG) Return the bytes for a blob_id (JPEG, normalized to max_dim; 0 &#x3D; raw bytes). Scoped keys can only fetch their own customer&#39;s items; other customers&#39; blobs are a 404 (never an existence leak).  ?waveform&#x3D;1 renders an audio blob&#39;s waveform as a PNG (ffmpeg showwavespic) so clients can show a real visual for audio hits without decoding the clip in the browser.
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="maxDim"> (optional, default to 1280)</param>
        /// <param name="waveform"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<LowdownLabs.Fever.Client.ApiResponse<Object>> GetMediaBytesWithHttpInfoAsync(int blobId, int? maxDim = default, int? waveform = default, System.Threading.CancellationToken cancellationToken = default)
        {

            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "image/jpeg",
                "image/png"
            };


            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("blob_id", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(blobId)); // path parameter
            if (maxDim != null)
            {
                localVarRequestOptions.QueryParameters.Add(LowdownLabs.Fever.Client.ClientUtils.ParameterToMultiMap("", "max_dim", maxDim));
            }
            if (waveform != null)
            {
                localVarRequestOptions.QueryParameters.Add(LowdownLabs.Fever.Client.ClientUtils.ParameterToMultiMap("", "waveform", waveform));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/media/{blob_id}/bytes", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMediaBytes", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Everything known about a blob: annotations, EXIF summary, media kind, derived artifact counts Unified record for a blob_id. Scoped keys can only read their own customer&#39;s blobs; other customers&#39; blobs are a 404 (never an existence leak). Admin keys may narrow with ?customer_id&#x3D;.
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>MediaInfo</returns>
        public MediaInfo GetMediaInfo(int blobId, string? customerId = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<MediaInfo> localVarResponse = GetMediaInfoWithHttpInfo(blobId, customerId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Everything known about a blob: annotations, EXIF summary, media kind, derived artifact counts Unified record for a blob_id. Scoped keys can only read their own customer&#39;s blobs; other customers&#39; blobs are a 404 (never an existence leak). Admin keys may narrow with ?customer_id&#x3D;.
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>ApiResponse of MediaInfo</returns>
        public LowdownLabs.Fever.Client.ApiResponse<MediaInfo> GetMediaInfoWithHttpInfo(int blobId, string? customerId = default)
        {
            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("blob_id", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(blobId)); // path parameter
            if (customerId != null)
            {
                localVarRequestOptions.QueryParameters.Add(LowdownLabs.Fever.Client.ClientUtils.ParameterToMultiMap("", "customer_id", customerId));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<MediaInfo>("/v1/media/{blob_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMediaInfo", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Everything known about a blob: annotations, EXIF summary, media kind, derived artifact counts Unified record for a blob_id. Scoped keys can only read their own customer&#39;s blobs; other customers&#39; blobs are a 404 (never an existence leak). Admin keys may narrow with ?customer_id&#x3D;.
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MediaInfo</returns>
        public async System.Threading.Tasks.Task<MediaInfo> GetMediaInfoAsync(int blobId, string? customerId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<MediaInfo> localVarResponse = await GetMediaInfoWithHttpInfoAsync(blobId, customerId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Everything known about a blob: annotations, EXIF summary, media kind, derived artifact counts Unified record for a blob_id. Scoped keys can only read their own customer&#39;s blobs; other customers&#39; blobs are a 404 (never an existence leak). Admin keys may narrow with ?customer_id&#x3D;.
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MediaInfo)</returns>
        public async System.Threading.Tasks.Task<LowdownLabs.Fever.Client.ApiResponse<MediaInfo>> GetMediaInfoWithHttpInfoAsync(int blobId, string? customerId = default, System.Threading.CancellationToken cancellationToken = default)
        {

            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("blob_id", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(blobId)); // path parameter
            if (customerId != null)
            {
                localVarRequestOptions.QueryParameters.Add(LowdownLabs.Fever.Client.ClientUtils.ParameterToMultiMap("", "customer_id", customerId));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<MediaInfo>("/v1/media/{blob_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMediaInfo", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Ingest capability: supported extensions per media family 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>MediaFormats</returns>
        public MediaFormats ListMediaFormats()
        {
            LowdownLabs.Fever.Client.ApiResponse<MediaFormats> localVarResponse = ListMediaFormatsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Ingest capability: supported extensions per media family 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of MediaFormats</returns>
        public LowdownLabs.Fever.Client.ApiResponse<MediaFormats> ListMediaFormatsWithHttpInfo()
        {
            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<MediaFormats>("/v1/media/formats", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListMediaFormats", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Ingest capability: supported extensions per media family 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MediaFormats</returns>
        public async System.Threading.Tasks.Task<MediaFormats> ListMediaFormatsAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<MediaFormats> localVarResponse = await ListMediaFormatsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Ingest capability: supported extensions per media family 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MediaFormats)</returns>
        public async System.Threading.Tasks.Task<LowdownLabs.Fever.Client.ApiResponse<MediaFormats>> ListMediaFormatsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<MediaFormats>("/v1/media/formats", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListMediaFormats", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sampled video frames for a parent blob 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>List&lt;MediaFrame&gt;</returns>
        public List<MediaFrame> ListMediaFrames(int blobId, string? customerId = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<List<MediaFrame>> localVarResponse = ListMediaFramesWithHttpInfo(blobId, customerId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Sampled video frames for a parent blob 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>ApiResponse of List&lt;MediaFrame&gt;</returns>
        public LowdownLabs.Fever.Client.ApiResponse<List<MediaFrame>> ListMediaFramesWithHttpInfo(int blobId, string? customerId = default)
        {
            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("blob_id", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(blobId)); // path parameter
            if (customerId != null)
            {
                localVarRequestOptions.QueryParameters.Add(LowdownLabs.Fever.Client.ClientUtils.ParameterToMultiMap("", "customer_id", customerId));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<MediaFrame>>("/v1/media/{blob_id}/frames", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListMediaFrames", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sampled video frames for a parent blob 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;MediaFrame&gt;</returns>
        public async System.Threading.Tasks.Task<List<MediaFrame>> ListMediaFramesAsync(int blobId, string? customerId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<List<MediaFrame>> localVarResponse = await ListMediaFramesWithHttpInfoAsync(blobId, customerId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Sampled video frames for a parent blob 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;MediaFrame&gt;)</returns>
        public async System.Threading.Tasks.Task<LowdownLabs.Fever.Client.ApiResponse<List<MediaFrame>>> ListMediaFramesWithHttpInfoAsync(int blobId, string? customerId = default, System.Threading.CancellationToken cancellationToken = default)
        {

            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("blob_id", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(blobId)); // path parameter
            if (customerId != null)
            {
                localVarRequestOptions.QueryParameters.Add(LowdownLabs.Fever.Client.ClientUtils.ParameterToMultiMap("", "customer_id", customerId));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<MediaFrame>>("/v1/media/{blob_id}/frames", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListMediaFrames", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Whisper transcript segments for a parent blob (audio or video) 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>List&lt;TranscriptSegment&gt;</returns>
        public List<TranscriptSegment> ListMediaTranscript(int blobId, string? customerId = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<List<TranscriptSegment>> localVarResponse = ListMediaTranscriptWithHttpInfo(blobId, customerId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Whisper transcript segments for a parent blob (audio or video) 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <returns>ApiResponse of List&lt;TranscriptSegment&gt;</returns>
        public LowdownLabs.Fever.Client.ApiResponse<List<TranscriptSegment>> ListMediaTranscriptWithHttpInfo(int blobId, string? customerId = default)
        {
            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("blob_id", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(blobId)); // path parameter
            if (customerId != null)
            {
                localVarRequestOptions.QueryParameters.Add(LowdownLabs.Fever.Client.ClientUtils.ParameterToMultiMap("", "customer_id", customerId));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<TranscriptSegment>>("/v1/media/{blob_id}/transcript", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListMediaTranscript", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Whisper transcript segments for a parent blob (audio or video) 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;TranscriptSegment&gt;</returns>
        public async System.Threading.Tasks.Task<List<TranscriptSegment>> ListMediaTranscriptAsync(int blobId, string? customerId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            LowdownLabs.Fever.Client.ApiResponse<List<TranscriptSegment>> localVarResponse = await ListMediaTranscriptWithHttpInfoAsync(blobId, customerId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Whisper transcript segments for a parent blob (audio or video) 
        /// </summary>
        /// <exception cref="LowdownLabs.Fever.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="blobId"></param>
        /// <param name="customerId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;TranscriptSegment&gt;)</returns>
        public async System.Threading.Tasks.Task<LowdownLabs.Fever.Client.ApiResponse<List<TranscriptSegment>>> ListMediaTranscriptWithHttpInfoAsync(int blobId, string? customerId = default, System.Threading.CancellationToken cancellationToken = default)
        {

            LowdownLabs.Fever.Client.RequestOptions localVarRequestOptions = new LowdownLabs.Fever.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = LowdownLabs.Fever.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("blob_id", LowdownLabs.Fever.Client.ClientUtils.ParameterToString(blobId)); // path parameter
            if (customerId != null)
            {
                localVarRequestOptions.QueryParameters.Add(LowdownLabs.Fever.Client.ClientUtils.ParameterToMultiMap("", "customer_id", customerId));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<TranscriptSegment>>("/v1/media/{blob_id}/transcript", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListMediaTranscript", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
