/*
 * FEVER Retrieval
 *
 * The multimodal media database. Images, video, audio, office documents, and LiDAR in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans, collection grouping, and asset-to-asset attachments. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IngestMedia {
    /// Optional caption/keywords; indexed at the highest text-search weight.
    #[serde(rename = "caption", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub caption: Option<Option<String>>,
    /// Optional grouping you own (project, case, site - FEVER stores and filters it, never interprets it). Filterable at search time; returned on hits.
    #[serde(rename = "collection_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub collection_id: Option<Option<String>>,
    /// Optional tag attributing this item to one of your customers; filterable at search time.
    #[serde(rename = "customer_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<Option<String>>,
    /// Base64-encoded media item bytes.
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<String>>,
    /// Original file name. Drives format detection for inline documents and LiDAR (extensions like .csv or .las - office formats are recognized by their bytes alone) and is stored on the blob for media info and attachment listings.
    #[serde(rename = "filename", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub filename: Option<Option<String>>,
    /// Opaque JSON returned with search hits.
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// Optional pointer to a related parent asset (its external_ref, key, or blob_id). Non-searchable companions such as LiDAR scans declare the photo or video they belong to; the parent's record lists them back as attachments.
    #[serde(rename = "parent_ref", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_ref: Option<Option<String>>,
    /// Skip EXIF extraction/retention for this item.
    #[serde(rename = "strip_exif", skip_serializing_if = "Option::is_none")]
    pub strip_exif: Option<bool>,
    /// Optional tags for this item; indexed for text search and returned on hits. Merged with the appliance's zero-shot autotags.
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<String>>>,
    /// An s3:// URI to one media item you already store, instead of inline bytes.
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
}

impl IngestMedia {
    pub fn new() -> IngestMedia {
        IngestMedia {
            caption: None,
            collection_id: None,
            customer_id: None,
            data: None,
            filename: None,
            metadata: None,
            parent_ref: None,
            strip_exif: None,
            tags: None,
            url: None,
        }
    }
}

