/*
 * FEVER Retrieval
 *
 * The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaInfo {
    #[serde(rename = "blob_id")]
    pub blob_id: i32,
    /// The user_text caption/keywords supplied at ingest.
    #[serde(rename = "caption", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub caption: Option<Option<String>>,
    /// EXIF capture time.
    #[serde(rename = "captured_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub captured_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "customer_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<Option<String>>,
    /// EXIF camera make/model.
    #[serde(rename = "device", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub device: Option<Option<String>>,
    /// s3:// URI of the stored original.
    #[serde(rename = "external_ref", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub external_ref: Option<Option<String>>,
    /// Sampled video frames derived from this blob.
    #[serde(rename = "frame_count", skip_serializing_if = "Option::is_none")]
    pub frame_count: Option<i32>,
    #[serde(rename = "gps_lat", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gps_lat: Option<Option<f64>>,
    #[serde(rename = "gps_lon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gps_lon: Option<Option<f64>>,
    /// Media kind of this blob (image/video/audio/pdf/doc/note).
    #[serde(rename = "kind", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub kind: Option<Option<Kind>>,
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// Text OCR'd out of the item (PDF pages always, photos when enabled).
    #[serde(rename = "ocr_text", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ocr_text: Option<Option<String>>,
    /// Likely-AI score in [0,1] (FEVER_SYNTHETIC), when scored.
    #[serde(rename = "synthetic", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub synthetic: Option<Option<f64>>,
    /// Client-supplied tags merged with zero-shot autotags.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Whisper transcript segments derived from this blob.
    #[serde(rename = "transcript_segments", skip_serializing_if = "Option::is_none")]
    pub transcript_segments: Option<i32>,
}

impl MediaInfo {
    pub fn new(blob_id: i32) -> MediaInfo {
        MediaInfo {
            blob_id,
            caption: None,
            captured_at: None,
            customer_id: None,
            device: None,
            external_ref: None,
            frame_count: None,
            gps_lat: None,
            gps_lon: None,
            kind: None,
            metadata: None,
            ocr_text: None,
            synthetic: None,
            tags: None,
            transcript_segments: None,
        }
    }
}
/// Media kind of this blob (image/video/audio/pdf/doc/note).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "image")]
    Image,
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "audio")]
    Audio,
    #[serde(rename = "pdf")]
    Pdf,
    #[serde(rename = "doc")]
    Doc,
    #[serde(rename = "note")]
    Note,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Image
    }
}

