/*
 * FEVER Retrieval
 * The multimodal media database. Images, video, audio, office documents, and LiDAR in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans, collection grouping, and asset-to-asset attachments. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lowdownlabs.fever.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.lowdownlabs.fever.ApiClient;
/**
 * DuplicatesRequest
 */
@JsonPropertyOrder({
  DuplicatesRequest.JSON_PROPERTY_CUSTOMER_ID,
  DuplicatesRequest.JSON_PROPERTY_CUSTOMER_IDS,
  DuplicatesRequest.JSON_PROPERTY_LIMIT,
  DuplicatesRequest.JSON_PROPERTY_THRESHOLD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DuplicatesRequest {
  public static final String JSON_PROPERTY_CUSTOMER_ID = "customer_id";
  private JsonNullable<String> customerId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CUSTOMER_IDS = "customer_ids";
  private JsonNullable<List<String>> customerIds = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @javax.annotation.Nullable
  private Integer limit = 500;

  public static final String JSON_PROPERTY_THRESHOLD = "threshold";
  @javax.annotation.Nullable
  private BigDecimal threshold = new BigDecimal("0.92");

  public DuplicatesRequest() { 
  }

  public DuplicatesRequest customerId(@javax.annotation.Nullable String customerId) {
    this.customerId = JsonNullable.<String>of(customerId);
    return this;
  }

  /**
   * Restrict the scan to media tagged with this customer_id. A scoped key is always forced to its own customer_id; an admin key may pass any customer_id or none (all customers).
   * @return customerId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getCustomerId() {
        return customerId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCustomerId_JsonNullable() {
    return customerId;
  }
  
  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  public void setCustomerId_JsonNullable(JsonNullable<String> customerId) {
    this.customerId = customerId;
  }

  public void setCustomerId(@javax.annotation.Nullable String customerId) {
    this.customerId = JsonNullable.<String>of(customerId);
  }


  public DuplicatesRequest customerIds(@javax.annotation.Nullable List<String> customerIds) {
    this.customerIds = JsonNullable.<List<String>>of(customerIds);
    return this;
  }

  public DuplicatesRequest addCustomerIdsItem(String customerIdsItem) {
    if (this.customerIds == null || !this.customerIds.isPresent() || this.customerIds.get() == null) {
      this.customerIds = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.customerIds.get().add(customerIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Admin only: restrict the scan to this set of customers. Spanning more than one customer is how cross-account duplicates (the same item submitted under different accounts) are found. Ignored for scoped keys, which stay pinned.
   * @return customerIds
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public List<String> getCustomerIds() {
        return customerIds.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getCustomerIds_JsonNullable() {
    return customerIds;
  }
  
  @JsonProperty(JSON_PROPERTY_CUSTOMER_IDS)
  public void setCustomerIds_JsonNullable(JsonNullable<List<String>> customerIds) {
    this.customerIds = customerIds;
  }

  public void setCustomerIds(@javax.annotation.Nullable List<String> customerIds) {
    this.customerIds = JsonNullable.<List<String>>of(customerIds);
  }


  public DuplicatesRequest limit(@javax.annotation.Nullable Integer limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Max items to scan for near-duplicates.
   * minimum: 1
   * maximum: 5000
   * @return limit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLimit(@javax.annotation.Nullable Integer limit) {
    this.limit = limit;
  }


  public DuplicatesRequest threshold(@javax.annotation.Nullable BigDecimal threshold) {
    this.threshold = threshold;
    return this;
  }

  /**
   * Similarity cutoff 0..1; higher is stricter (1.0 &#x3D; near-identical).
   * minimum: 0.0
   * maximum: 1.0
   * @return threshold
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THRESHOLD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getThreshold() {
    return threshold;
  }


  @JsonProperty(value = JSON_PROPERTY_THRESHOLD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThreshold(@javax.annotation.Nullable BigDecimal threshold) {
    this.threshold = threshold;
  }


  /**
   * Return true if this DuplicatesRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DuplicatesRequest duplicatesRequest = (DuplicatesRequest) o;
    return equalsNullable(this.customerId, duplicatesRequest.customerId) &&
        equalsNullable(this.customerIds, duplicatesRequest.customerIds) &&
        Objects.equals(this.limit, duplicatesRequest.limit) &&
        Objects.equals(this.threshold, duplicatesRequest.threshold);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(customerId), hashCodeNullable(customerIds), limit, threshold);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DuplicatesRequest {\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    customerIds: ").append(toIndentedString(customerIds)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `customer_id` to the URL query string
    if (getCustomerId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scustomer_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCustomerId()))));
    }

    // add `customer_ids` to the URL query string
    if (getCustomerIds() != null) {
      for (int i = 0; i < getCustomerIds().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scustomer_ids%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getCustomerIds().get(i)))));
      }
    }

    // add `limit` to the URL query string
    if (getLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slimit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLimit()))));
    }

    // add `threshold` to the URL query string
    if (getThreshold() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sthreshold%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getThreshold()))));
    }

    return joiner.toString();
  }
}

