/*
FEVER Retrieval

The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fever

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchHit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchHit{}

// SearchHit struct for SearchHit
type SearchHit struct {
	BlobId int32 `json:"blob_id"`
	Caption NullableString `json:"caption,omitempty"`
	CustomerId NullableString `json:"customer_id,omitempty"`
	// Number of near-duplicates collapsed into this hit.
	DuplicateCount *int32 `json:"duplicate_count,omitempty"`
	// blob_ids of near-duplicates collapsed into this hit.
	Duplicates []int32 `json:"duplicates,omitempty"`
	// Reverse-geocode label from EXIF GPS (e.g. 'Lisbon, PT'), when the asset carries intact camera coordinates (the geo:<label> tag rides alongside).
	GeoLabel NullableString `json:"geo_label,omitempty"`
	// Lexical FTS highlight (ts_headline) when the hit came via full-text search.
	Headline NullableString `json:"headline,omitempty"`
	// Stored media height in pixels, when known.
	Height NullableInt32 `json:"height,omitempty"`
	// Media kind of this hit's parent blob.
	Kind NullableString `json:"kind,omitempty"`
	// s3:// URI of the matched media item.
	MediaRef NullableString `json:"media_ref,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// For score_type 'rerank' this is the model's match probability in [0,1] (a calibrated confidence); 'cosine' is vector similarity; 'rrf' is a lexical rank score.
	Score float32 `json:"score"`
	ScoreType string `json:"score_type"`
	// For video hits: timestamp of the winning frame, for seek-to-moment playback.
	SeekMs NullableInt32 `json:"seek_ms,omitempty"`
	// For transcript hits: the matching whisper segment, with literal text for highlighting.
	Span NullableMediaSpan `json:"span,omitempty"`
	// Lexical FTS highlight (ts_headline) of the winning transcript segment.
	SpanHeadline NullableString `json:"span_headline,omitempty"`
	// Tags on this item: client-supplied at ingest and/or the appliance's zero-shot autotags.
	Tags []string `json:"tags,omitempty"`
	// Stored media width in pixels, when known.
	Width NullableInt32 `json:"width,omitempty"`
}

type _SearchHit SearchHit

// NewSearchHit instantiates a new SearchHit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchHit(blobId int32, score float32, scoreType string) *SearchHit {
	this := SearchHit{}
	this.BlobId = blobId
	var duplicateCount int32 = 0
	this.DuplicateCount = &duplicateCount
	this.Score = score
	this.ScoreType = scoreType
	return &this
}

// NewSearchHitWithDefaults instantiates a new SearchHit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchHitWithDefaults() *SearchHit {
	this := SearchHit{}
	var duplicateCount int32 = 0
	this.DuplicateCount = &duplicateCount
	return &this
}

// GetBlobId returns the BlobId field value
func (o *SearchHit) GetBlobId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BlobId
}

// GetBlobIdOk returns a tuple with the BlobId field value
// and a boolean to check if the value has been set.
func (o *SearchHit) GetBlobIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlobId, true
}

// SetBlobId sets field value
func (o *SearchHit) SetBlobId(v int32) {
	o.BlobId = v
}

// GetCaption returns the Caption field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchHit) GetCaption() string {
	if o == nil || IsNil(o.Caption.Get()) {
		var ret string
		return ret
	}
	return *o.Caption.Get()
}

// GetCaptionOk returns a tuple with the Caption field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchHit) GetCaptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Caption.Get(), o.Caption.IsSet()
}

// HasCaption returns a boolean if a field has been set.
func (o *SearchHit) HasCaption() bool {
	if o != nil && o.Caption.IsSet() {
		return true
	}

	return false
}

// SetCaption gets a reference to the given NullableString and assigns it to the Caption field.
func (o *SearchHit) SetCaption(v string) {
	o.Caption.Set(&v)
}
// SetCaptionNil sets the value for Caption to be an explicit nil
func (o *SearchHit) SetCaptionNil() {
	o.Caption.Set(nil)
}

// UnsetCaption ensures that no value is present for Caption, not even an explicit nil
func (o *SearchHit) UnsetCaption() {
	o.Caption.Unset()
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchHit) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerId.Get()
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchHit) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerId.Get(), o.CustomerId.IsSet()
}

// HasCustomerId returns a boolean if a field has been set.
func (o *SearchHit) HasCustomerId() bool {
	if o != nil && o.CustomerId.IsSet() {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given NullableString and assigns it to the CustomerId field.
func (o *SearchHit) SetCustomerId(v string) {
	o.CustomerId.Set(&v)
}
// SetCustomerIdNil sets the value for CustomerId to be an explicit nil
func (o *SearchHit) SetCustomerIdNil() {
	o.CustomerId.Set(nil)
}

// UnsetCustomerId ensures that no value is present for CustomerId, not even an explicit nil
func (o *SearchHit) UnsetCustomerId() {
	o.CustomerId.Unset()
}

// GetDuplicateCount returns the DuplicateCount field value if set, zero value otherwise.
func (o *SearchHit) GetDuplicateCount() int32 {
	if o == nil || IsNil(o.DuplicateCount) {
		var ret int32
		return ret
	}
	return *o.DuplicateCount
}

// GetDuplicateCountOk returns a tuple with the DuplicateCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchHit) GetDuplicateCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DuplicateCount) {
		return nil, false
	}
	return o.DuplicateCount, true
}

// HasDuplicateCount returns a boolean if a field has been set.
func (o *SearchHit) HasDuplicateCount() bool {
	if o != nil && !IsNil(o.DuplicateCount) {
		return true
	}

	return false
}

// SetDuplicateCount gets a reference to the given int32 and assigns it to the DuplicateCount field.
func (o *SearchHit) SetDuplicateCount(v int32) {
	o.DuplicateCount = &v
}

// GetDuplicates returns the Duplicates field value if set, zero value otherwise.
func (o *SearchHit) GetDuplicates() []int32 {
	if o == nil || IsNil(o.Duplicates) {
		var ret []int32
		return ret
	}
	return o.Duplicates
}

// GetDuplicatesOk returns a tuple with the Duplicates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchHit) GetDuplicatesOk() ([]int32, bool) {
	if o == nil || IsNil(o.Duplicates) {
		return nil, false
	}
	return o.Duplicates, true
}

// HasDuplicates returns a boolean if a field has been set.
func (o *SearchHit) HasDuplicates() bool {
	if o != nil && !IsNil(o.Duplicates) {
		return true
	}

	return false
}

// SetDuplicates gets a reference to the given []int32 and assigns it to the Duplicates field.
func (o *SearchHit) SetDuplicates(v []int32) {
	o.Duplicates = v
}

// GetGeoLabel returns the GeoLabel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchHit) GetGeoLabel() string {
	if o == nil || IsNil(o.GeoLabel.Get()) {
		var ret string
		return ret
	}
	return *o.GeoLabel.Get()
}

// GetGeoLabelOk returns a tuple with the GeoLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchHit) GetGeoLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GeoLabel.Get(), o.GeoLabel.IsSet()
}

// HasGeoLabel returns a boolean if a field has been set.
func (o *SearchHit) HasGeoLabel() bool {
	if o != nil && o.GeoLabel.IsSet() {
		return true
	}

	return false
}

// SetGeoLabel gets a reference to the given NullableString and assigns it to the GeoLabel field.
func (o *SearchHit) SetGeoLabel(v string) {
	o.GeoLabel.Set(&v)
}
// SetGeoLabelNil sets the value for GeoLabel to be an explicit nil
func (o *SearchHit) SetGeoLabelNil() {
	o.GeoLabel.Set(nil)
}

// UnsetGeoLabel ensures that no value is present for GeoLabel, not even an explicit nil
func (o *SearchHit) UnsetGeoLabel() {
	o.GeoLabel.Unset()
}

// GetHeadline returns the Headline field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchHit) GetHeadline() string {
	if o == nil || IsNil(o.Headline.Get()) {
		var ret string
		return ret
	}
	return *o.Headline.Get()
}

// GetHeadlineOk returns a tuple with the Headline field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchHit) GetHeadlineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Headline.Get(), o.Headline.IsSet()
}

// HasHeadline returns a boolean if a field has been set.
func (o *SearchHit) HasHeadline() bool {
	if o != nil && o.Headline.IsSet() {
		return true
	}

	return false
}

// SetHeadline gets a reference to the given NullableString and assigns it to the Headline field.
func (o *SearchHit) SetHeadline(v string) {
	o.Headline.Set(&v)
}
// SetHeadlineNil sets the value for Headline to be an explicit nil
func (o *SearchHit) SetHeadlineNil() {
	o.Headline.Set(nil)
}

// UnsetHeadline ensures that no value is present for Headline, not even an explicit nil
func (o *SearchHit) UnsetHeadline() {
	o.Headline.Unset()
}

// GetHeight returns the Height field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchHit) GetHeight() int32 {
	if o == nil || IsNil(o.Height.Get()) {
		var ret int32
		return ret
	}
	return *o.Height.Get()
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchHit) GetHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Height.Get(), o.Height.IsSet()
}

// HasHeight returns a boolean if a field has been set.
func (o *SearchHit) HasHeight() bool {
	if o != nil && o.Height.IsSet() {
		return true
	}

	return false
}

// SetHeight gets a reference to the given NullableInt32 and assigns it to the Height field.
func (o *SearchHit) SetHeight(v int32) {
	o.Height.Set(&v)
}
// SetHeightNil sets the value for Height to be an explicit nil
func (o *SearchHit) SetHeightNil() {
	o.Height.Set(nil)
}

// UnsetHeight ensures that no value is present for Height, not even an explicit nil
func (o *SearchHit) UnsetHeight() {
	o.Height.Unset()
}

// GetKind returns the Kind field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchHit) GetKind() string {
	if o == nil || IsNil(o.Kind.Get()) {
		var ret string
		return ret
	}
	return *o.Kind.Get()
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchHit) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Kind.Get(), o.Kind.IsSet()
}

// HasKind returns a boolean if a field has been set.
func (o *SearchHit) HasKind() bool {
	if o != nil && o.Kind.IsSet() {
		return true
	}

	return false
}

// SetKind gets a reference to the given NullableString and assigns it to the Kind field.
func (o *SearchHit) SetKind(v string) {
	o.Kind.Set(&v)
}
// SetKindNil sets the value for Kind to be an explicit nil
func (o *SearchHit) SetKindNil() {
	o.Kind.Set(nil)
}

// UnsetKind ensures that no value is present for Kind, not even an explicit nil
func (o *SearchHit) UnsetKind() {
	o.Kind.Unset()
}

// GetMediaRef returns the MediaRef field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchHit) GetMediaRef() string {
	if o == nil || IsNil(o.MediaRef.Get()) {
		var ret string
		return ret
	}
	return *o.MediaRef.Get()
}

// GetMediaRefOk returns a tuple with the MediaRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchHit) GetMediaRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MediaRef.Get(), o.MediaRef.IsSet()
}

// HasMediaRef returns a boolean if a field has been set.
func (o *SearchHit) HasMediaRef() bool {
	if o != nil && o.MediaRef.IsSet() {
		return true
	}

	return false
}

// SetMediaRef gets a reference to the given NullableString and assigns it to the MediaRef field.
func (o *SearchHit) SetMediaRef(v string) {
	o.MediaRef.Set(&v)
}
// SetMediaRefNil sets the value for MediaRef to be an explicit nil
func (o *SearchHit) SetMediaRefNil() {
	o.MediaRef.Set(nil)
}

// UnsetMediaRef ensures that no value is present for MediaRef, not even an explicit nil
func (o *SearchHit) UnsetMediaRef() {
	o.MediaRef.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchHit) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchHit) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *SearchHit) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *SearchHit) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetScore returns the Score field value
func (o *SearchHit) GetScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Score
}

// GetScoreOk returns a tuple with the Score field value
// and a boolean to check if the value has been set.
func (o *SearchHit) GetScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Score, true
}

// SetScore sets field value
func (o *SearchHit) SetScore(v float32) {
	o.Score = v
}

// GetScoreType returns the ScoreType field value
func (o *SearchHit) GetScoreType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScoreType
}

// GetScoreTypeOk returns a tuple with the ScoreType field value
// and a boolean to check if the value has been set.
func (o *SearchHit) GetScoreTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScoreType, true
}

// SetScoreType sets field value
func (o *SearchHit) SetScoreType(v string) {
	o.ScoreType = v
}

// GetSeekMs returns the SeekMs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchHit) GetSeekMs() int32 {
	if o == nil || IsNil(o.SeekMs.Get()) {
		var ret int32
		return ret
	}
	return *o.SeekMs.Get()
}

// GetSeekMsOk returns a tuple with the SeekMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchHit) GetSeekMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SeekMs.Get(), o.SeekMs.IsSet()
}

// HasSeekMs returns a boolean if a field has been set.
func (o *SearchHit) HasSeekMs() bool {
	if o != nil && o.SeekMs.IsSet() {
		return true
	}

	return false
}

// SetSeekMs gets a reference to the given NullableInt32 and assigns it to the SeekMs field.
func (o *SearchHit) SetSeekMs(v int32) {
	o.SeekMs.Set(&v)
}
// SetSeekMsNil sets the value for SeekMs to be an explicit nil
func (o *SearchHit) SetSeekMsNil() {
	o.SeekMs.Set(nil)
}

// UnsetSeekMs ensures that no value is present for SeekMs, not even an explicit nil
func (o *SearchHit) UnsetSeekMs() {
	o.SeekMs.Unset()
}

// GetSpan returns the Span field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchHit) GetSpan() MediaSpan {
	if o == nil || IsNil(o.Span.Get()) {
		var ret MediaSpan
		return ret
	}
	return *o.Span.Get()
}

// GetSpanOk returns a tuple with the Span field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchHit) GetSpanOk() (*MediaSpan, bool) {
	if o == nil {
		return nil, false
	}
	return o.Span.Get(), o.Span.IsSet()
}

// HasSpan returns a boolean if a field has been set.
func (o *SearchHit) HasSpan() bool {
	if o != nil && o.Span.IsSet() {
		return true
	}

	return false
}

// SetSpan gets a reference to the given NullableMediaSpan and assigns it to the Span field.
func (o *SearchHit) SetSpan(v MediaSpan) {
	o.Span.Set(&v)
}
// SetSpanNil sets the value for Span to be an explicit nil
func (o *SearchHit) SetSpanNil() {
	o.Span.Set(nil)
}

// UnsetSpan ensures that no value is present for Span, not even an explicit nil
func (o *SearchHit) UnsetSpan() {
	o.Span.Unset()
}

// GetSpanHeadline returns the SpanHeadline field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchHit) GetSpanHeadline() string {
	if o == nil || IsNil(o.SpanHeadline.Get()) {
		var ret string
		return ret
	}
	return *o.SpanHeadline.Get()
}

// GetSpanHeadlineOk returns a tuple with the SpanHeadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchHit) GetSpanHeadlineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpanHeadline.Get(), o.SpanHeadline.IsSet()
}

// HasSpanHeadline returns a boolean if a field has been set.
func (o *SearchHit) HasSpanHeadline() bool {
	if o != nil && o.SpanHeadline.IsSet() {
		return true
	}

	return false
}

// SetSpanHeadline gets a reference to the given NullableString and assigns it to the SpanHeadline field.
func (o *SearchHit) SetSpanHeadline(v string) {
	o.SpanHeadline.Set(&v)
}
// SetSpanHeadlineNil sets the value for SpanHeadline to be an explicit nil
func (o *SearchHit) SetSpanHeadlineNil() {
	o.SpanHeadline.Set(nil)
}

// UnsetSpanHeadline ensures that no value is present for SpanHeadline, not even an explicit nil
func (o *SearchHit) UnsetSpanHeadline() {
	o.SpanHeadline.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SearchHit) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchHit) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SearchHit) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *SearchHit) SetTags(v []string) {
	o.Tags = v
}

// GetWidth returns the Width field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchHit) GetWidth() int32 {
	if o == nil || IsNil(o.Width.Get()) {
		var ret int32
		return ret
	}
	return *o.Width.Get()
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchHit) GetWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Width.Get(), o.Width.IsSet()
}

// HasWidth returns a boolean if a field has been set.
func (o *SearchHit) HasWidth() bool {
	if o != nil && o.Width.IsSet() {
		return true
	}

	return false
}

// SetWidth gets a reference to the given NullableInt32 and assigns it to the Width field.
func (o *SearchHit) SetWidth(v int32) {
	o.Width.Set(&v)
}
// SetWidthNil sets the value for Width to be an explicit nil
func (o *SearchHit) SetWidthNil() {
	o.Width.Set(nil)
}

// UnsetWidth ensures that no value is present for Width, not even an explicit nil
func (o *SearchHit) UnsetWidth() {
	o.Width.Unset()
}

func (o SearchHit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchHit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["blob_id"] = o.BlobId
	if o.Caption.IsSet() {
		toSerialize["caption"] = o.Caption.Get()
	}
	if o.CustomerId.IsSet() {
		toSerialize["customer_id"] = o.CustomerId.Get()
	}
	if !IsNil(o.DuplicateCount) {
		toSerialize["duplicate_count"] = o.DuplicateCount
	}
	if !IsNil(o.Duplicates) {
		toSerialize["duplicates"] = o.Duplicates
	}
	if o.GeoLabel.IsSet() {
		toSerialize["geo_label"] = o.GeoLabel.Get()
	}
	if o.Headline.IsSet() {
		toSerialize["headline"] = o.Headline.Get()
	}
	if o.Height.IsSet() {
		toSerialize["height"] = o.Height.Get()
	}
	if o.Kind.IsSet() {
		toSerialize["kind"] = o.Kind.Get()
	}
	if o.MediaRef.IsSet() {
		toSerialize["media_ref"] = o.MediaRef.Get()
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["score"] = o.Score
	toSerialize["score_type"] = o.ScoreType
	if o.SeekMs.IsSet() {
		toSerialize["seek_ms"] = o.SeekMs.Get()
	}
	if o.Span.IsSet() {
		toSerialize["span"] = o.Span.Get()
	}
	if o.SpanHeadline.IsSet() {
		toSerialize["span_headline"] = o.SpanHeadline.Get()
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.Width.IsSet() {
		toSerialize["width"] = o.Width.Get()
	}
	return toSerialize, nil
}

func (o *SearchHit) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"blob_id",
		"score",
		"score_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchHit := _SearchHit{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchHit)

	if err != nil {
		return err
	}

	*o = SearchHit(varSearchHit)

	return err
}

type NullableSearchHit struct {
	value *SearchHit
	isSet bool
}

func (v NullableSearchHit) Get() *SearchHit {
	return v.value
}

func (v *NullableSearchHit) Set(val *SearchHit) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchHit) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchHit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchHit(val *SearchHit) *NullableSearchHit {
	return &NullableSearchHit{value: val, isSet: true}
}

func (v NullableSearchHit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchHit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


