/*
FEVER Retrieval

The multimodal media database. Images, video, audio, office documents, and LiDAR in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans, collection grouping, and asset-to-asset attachments. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fever

import (
	"encoding/json"
)

// checks if the CreateKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateKeyRequest{}

// CreateKeyRequest struct for CreateKeyRequest
type CreateKeyRequest struct {
	// For a scoped key, the single customer_id every request with this key is forced to. Must be empty for an admin key.
	CustomerId NullableString `json:"customer_id,omitempty"`
	// Optional label for this API key (e.g. which app or integration uses it).
	Name NullableString `json:"name,omitempty"`
	// 'admin' keys search/ingest across all customers and may pass any customer_id; 'scoped' keys are locked server-side to one customer_id. If omitted it is inferred from customer_id (present means scoped, absent means admin).
	Role NullableString `json:"role,omitempty"`
}

// NewCreateKeyRequest instantiates a new CreateKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateKeyRequest() *CreateKeyRequest {
	this := CreateKeyRequest{}
	return &this
}

// NewCreateKeyRequestWithDefaults instantiates a new CreateKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateKeyRequestWithDefaults() *CreateKeyRequest {
	this := CreateKeyRequest{}
	return &this
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateKeyRequest) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerId.Get()
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateKeyRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerId.Get(), o.CustomerId.IsSet()
}

// HasCustomerId returns a boolean if a field has been set.
func (o *CreateKeyRequest) HasCustomerId() bool {
	if o != nil && o.CustomerId.IsSet() {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given NullableString and assigns it to the CustomerId field.
func (o *CreateKeyRequest) SetCustomerId(v string) {
	o.CustomerId.Set(&v)
}
// SetCustomerIdNil sets the value for CustomerId to be an explicit nil
func (o *CreateKeyRequest) SetCustomerIdNil() {
	o.CustomerId.Set(nil)
}

// UnsetCustomerId ensures that no value is present for CustomerId, not even an explicit nil
func (o *CreateKeyRequest) UnsetCustomerId() {
	o.CustomerId.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateKeyRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateKeyRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *CreateKeyRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *CreateKeyRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *CreateKeyRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *CreateKeyRequest) UnsetName() {
	o.Name.Unset()
}

// GetRole returns the Role field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateKeyRequest) GetRole() string {
	if o == nil || IsNil(o.Role.Get()) {
		var ret string
		return ret
	}
	return *o.Role.Get()
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateKeyRequest) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Role.Get(), o.Role.IsSet()
}

// HasRole returns a boolean if a field has been set.
func (o *CreateKeyRequest) HasRole() bool {
	if o != nil && o.Role.IsSet() {
		return true
	}

	return false
}

// SetRole gets a reference to the given NullableString and assigns it to the Role field.
func (o *CreateKeyRequest) SetRole(v string) {
	o.Role.Set(&v)
}
// SetRoleNil sets the value for Role to be an explicit nil
func (o *CreateKeyRequest) SetRoleNil() {
	o.Role.Set(nil)
}

// UnsetRole ensures that no value is present for Role, not even an explicit nil
func (o *CreateKeyRequest) UnsetRole() {
	o.Role.Unset()
}

func (o CreateKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CustomerId.IsSet() {
		toSerialize["customer_id"] = o.CustomerId.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Role.IsSet() {
		toSerialize["role"] = o.Role.Get()
	}
	return toSerialize, nil
}

type NullableCreateKeyRequest struct {
	value *CreateKeyRequest
	isSet bool
}

func (v NullableCreateKeyRequest) Get() *CreateKeyRequest {
	return v.value
}

func (v *NullableCreateKeyRequest) Set(val *CreateKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateKeyRequest(val *CreateKeyRequest) *NullableCreateKeyRequest {
	return &NullableCreateKeyRequest{value: val, isSet: true}
}

func (v NullableCreateKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


