=begin
#FEVER Retrieval

#The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FeverClient::IngestedMedia
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FeverClient::IngestedMedia do
  #let(:instance) { FeverClient::IngestedMedia.new }

  describe 'test an instance of IngestedMedia' do
    it 'should create an instance of IngestedMedia' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FeverClient::IngestedMedia)
    end
  end

  describe 'test attribute "blob_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "external_ref"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
