=begin
#FEVER Retrieval

#The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FeverClient::IngestApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IngestApi' do
  before do
    # run before each test
    @api_instance = FeverClient::IngestApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IngestApi' do
    it 'should create an instance of IngestApi' do
      expect(@api_instance).to be_instance_of(FeverClient::IngestApi)
    end
  end

  # unit tests for ingest_media
  # Ingest one or many media items
  # Throw 1..N media items over the wall. Small inline batches are embedded and indexed synchronously and return blob ids; large batches or an s3:// source return a Job you poll at /v1/jobs/{id}. Tenant is taken from the API key.
  # @param ingest_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization 
  # @return [IngestResult]
  describe 'ingest_media test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
