=begin
#FEVER Retrieval

#The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FeverClient::MediaApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MediaApi' do
  before do
    # run before each test
    @api_instance = FeverClient::MediaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MediaApi' do
    it 'should create an instance of MediaApi' do
      expect(@api_instance).to be_instance_of(FeverClient::MediaApi)
    end
  end

  # unit tests for get_media_bytes
  # Fetch an indexed media item&#39;s bytes (images normalized to JPEG)
  # Return the bytes for a blob_id (JPEG, normalized to max_dim; 0 &#x3D; raw bytes). Scoped keys can only fetch their own customer&#39;s items; other customers&#39; blobs are a 404 (never an existence leak).  ?waveform&#x3D;1 renders an audio blob&#39;s waveform as a PNG (ffmpeg showwavespic) so clients can show a real visual for audio hits without decoding the clip in the browser.
  # @param blob_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :max_dim 
  # @option opts [Integer] :waveform 
  # @option opts [String] :authorization 
  # @return [Object]
  describe 'get_media_bytes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_media_info
  # Everything known about a blob: annotations, EXIF summary, media kind, derived artifact counts
  # Unified record for a blob_id. Scoped keys can only read their own customer&#39;s blobs; other customers&#39; blobs are a 404 (never an existence leak). Admin keys may narrow with ?customer_id&#x3D;.
  # @param blob_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :customer_id 
  # @option opts [String] :authorization 
  # @return [MediaInfo]
  describe 'get_media_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_media_formats
  # Ingest capability: supported extensions per media family
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization 
  # @return [MediaFormats]
  describe 'list_media_formats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_media_frames
  # Sampled video frames for a parent blob
  # @param blob_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :customer_id 
  # @option opts [String] :authorization 
  # @return [Array<MediaFrame>]
  describe 'list_media_frames test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_media_transcript
  # Whisper transcript segments for a parent blob (audio or video)
  # @param blob_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :customer_id 
  # @option opts [String] :authorization 
  # @return [Array<TranscriptSegment>]
  describe 'list_media_transcript test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
