# coding: utf-8

"""
    FEVER Retrieval

    The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fever_client.models.ingested_media import IngestedMedia

class TestIngestedMedia(unittest.TestCase):
    """IngestedMedia unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IngestedMedia:
        """Test IngestedMedia
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IngestedMedia`
        """
        model = IngestedMedia()
        if include_optional:
            return IngestedMedia(
                blob_id = 56,
                external_ref = ''
            )
        else:
            return IngestedMedia(
                blob_id = 56,
        )
        """

    def testIngestedMedia(self):
        """Test IngestedMedia"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
