# coding: utf-8

"""
    FEVER Retrieval

    The multimodal media database. Images, video, audio, office documents, and LiDAR in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans, collection grouping, and asset-to-asset attachments. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fever_client.api.customers_api import CustomersApi


class TestCustomersApi(unittest.IsolatedAsyncioTestCase):
    """CustomersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CustomersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_reassign_customers_bulk(self) -> None:
        """Test case for reassign_customers_bulk

        Reassign customer_id in bulk from a JSONL / CSV / Parquet mapping
        """
        pass


if __name__ == '__main__':
    unittest.main()
