# coding: utf-8

"""
    FEVER Retrieval

    The multimodal media database. Images, video, audio, office documents, and LiDAR in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans, collection grouping, and asset-to-asset attachments. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fever_client.models.ingest_media import IngestMedia

class TestIngestMedia(unittest.TestCase):
    """IngestMedia unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IngestMedia:
        """Test IngestMedia
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IngestMedia`
        """
        model = IngestMedia()
        if include_optional:
            return IngestMedia(
                caption = '',
                collection_id = '',
                customer_id = '',
                data = '',
                filename = '',
                metadata = { },
                parent_ref = '',
                strip_exif = True,
                tags = [
                    ''
                    ],
                url = ''
            )
        else:
            return IngestMedia(
        )
        """

    def testIngestMedia(self):
        """Test IngestMedia"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
