/*
 * FEVER Retrieval
 * The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.lowdownlabs.fever.ApiException;
import org.openapitools.client.model.ExportRequest;
import org.openapitools.client.model.ExportResult;
import org.openapitools.client.model.HTTPValidationError;
import org.openapitools.client.model.ImportRequest;
import org.openapitools.client.model.ImportResult;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for ExportApi
 */
@Disabled
public class ExportApiTest {

    private final ExportApi api = new ExportApi();

    
    /**
     * Export the tenant&#39;s vectors and metadata to S3
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void exportTenantTest() throws ApiException {
        ExportRequest exportRequest = null;
        String authorization = null;
        ExportResult response = 
        api.exportTenant(exportRequest, authorization);
        
        // TODO: test validations
    }
    
    /**
     * Import vectors and metadata from a previous FEVER export in S3
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void importTenantTest() throws ApiException {
        ImportRequest importRequest = null;
        String authorization = null;
        ImportResult response = 
        api.importTenant(importRequest, authorization);
        
        // TODO: test validations
    }
    
}
