/* tslint:disable */
/* eslint-disable */
/**
 * FEVER Retrieval
 * The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CorpusTag
 */
export interface CorpusTag {
    /**
     * 
     */
    count: number;
    /**
     * 
     */
    tag: string;
}

/**
 * Check if a given object implements the CorpusTag interface.
 */
export function instanceOfCorpusTag(value: object): value is CorpusTag {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    return true;
}

export function CorpusTagFromJSON(json: any): CorpusTag {
    return CorpusTagFromJSONTyped(json, false);
}

export function CorpusTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorpusTag {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'tag': json['tag'],
    };
}

export function CorpusTagToJSON(json: any): CorpusTag {
    return CorpusTagToJSONTyped(json, false);
}

export function CorpusTagToJSONTyped(value?: CorpusTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'tag': value['tag'],
    };
}

