/* tslint:disable */
/* eslint-disable */
/**
 * FEVER Retrieval
 * The multimodal media database. Images, video, audio, office documents, and LiDAR in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans, collection grouping, and asset-to-asset attachments. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DuplicateCluster
 */
export interface DuplicateCluster {
    /**
     * customer_id of each member, parallel to members; a cluster whose distinct customer count exceeds 1 is duplicated across accounts.
     */
    memberCustomers?: Array<string | null>;
    /**
     * blob_ids of the items in this cluster.
     */
    members: Array<number>;
    /**
     * Number of items in this near-duplicate cluster.
     */
    size: number;
    /**
     * Minimum pairwise cosine similarity across the cluster.
     */
    tightness: number;
}

/**
 * Check if a given object implements the DuplicateCluster interface.
 */
export function instanceOfDuplicateCluster(value: object): value is DuplicateCluster {
    if (!('members' in value) || value['members'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('tightness' in value) || value['tightness'] === undefined) return false;
    return true;
}

export function DuplicateClusterFromJSON(json: any): DuplicateCluster {
    return DuplicateClusterFromJSONTyped(json, false);
}

export function DuplicateClusterFromJSONTyped(json: any, ignoreDiscriminator: boolean): DuplicateCluster {
    if (json == null) {
        return json;
    }
    return {
        
        'memberCustomers': json['member_customers'] == null ? undefined : json['member_customers'],
        'members': json['members'],
        'size': json['size'],
        'tightness': json['tightness'],
    };
}

export function DuplicateClusterToJSON(json: any): DuplicateCluster {
    return DuplicateClusterToJSONTyped(json, false);
}

export function DuplicateClusterToJSONTyped(value?: DuplicateCluster | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member_customers': value['memberCustomers'],
        'members': value['members'],
        'size': value['size'],
        'tightness': value['tightness'],
    };
}

