/* tslint:disable */
/* eslint-disable */
/**
 * FEVER Retrieval
 * The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportRequest
 */
export interface ImportRequest {
    /**
     * Tag every imported row with this customer_id (admin default: preserve the file's own).
     */
    customerId?: string | null;
    /**
     * s3://bucket/prefix of a previous FEVER export (manifest.json + shard NDJSON).
     */
    s3Uri: string;
}

/**
 * Check if a given object implements the ImportRequest interface.
 */
export function instanceOfImportRequest(value: object): value is ImportRequest {
    if ((!('s3Uri' in (value as Record<string, any>)) && !('s3_uri' in (value as Record<string, any>))) || ((value as Record<string, any>)['s3Uri'] === undefined && (value as Record<string, any>)['s3_uri'] === undefined)) return false;
    return true;
}

export function ImportRequestFromJSON(json: any): ImportRequest {
    return ImportRequestFromJSONTyped(json, false);
}

export function ImportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['customer_id'] === undefined ? undefined : json['customer_id'] === null ? null : json['customer_id'],
        's3Uri': json['s3_uri'],
    };
}

export function ImportRequestToJSON(json: any): ImportRequest {
    return ImportRequestToJSONTyped(json, false);
}

export function ImportRequestToJSONTyped(value?: ImportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customer_id': value['customerId'],
        's3_uri': value['s3Uri'],
    };
}

