/* tslint:disable */
/* eslint-disable */
/**
 * FEVER Retrieval
 * The multimodal media database. Images, video, audio, office documents, and LiDAR in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans, collection grouping, and asset-to-asset attachments. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestMedia
 */
export interface IngestMedia {
    /**
     * Optional caption/keywords; indexed at the highest text-search weight.
     */
    caption?: string | null;
    /**
     * Optional grouping you own (project, case, site - FEVER stores and filters it, never interprets it). Filterable at search time; returned on hits.
     */
    collectionId?: string | null;
    /**
     * Optional tag attributing this item to one of your customers; filterable at search time.
     */
    customerId?: string | null;
    /**
     * Base64-encoded media item bytes.
     */
    data?: string | null;
    /**
     * Original file name. Drives format detection for inline documents and LiDAR (extensions like .csv or .las - office formats are recognized by their bytes alone) and is stored on the blob for media info and attachment listings.
     */
    filename?: string | null;
    /**
     * Opaque JSON returned with search hits.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * Optional pointer to a related parent asset (its external_ref, key, or blob_id). Non-searchable companions such as LiDAR scans declare the photo or video they belong to; the parent's record lists them back as attachments.
     */
    parentRef?: string | null;
    /**
     * Skip EXIF extraction/retention for this item.
     */
    stripExif?: boolean;
    /**
     * Optional tags for this item; indexed for text search and returned on hits. Merged with the appliance's zero-shot autotags.
     */
    tags?: Array<string> | null;
    /**
     * An s3:// URI to one media item you already store, instead of inline bytes.
     */
    url?: string | null;
}

/**
 * Check if a given object implements the IngestMedia interface.
 */
export function instanceOfIngestMedia(value: object): value is IngestMedia {
    return true;
}

export function IngestMediaFromJSON(json: any): IngestMedia {
    return IngestMediaFromJSONTyped(json, false);
}

export function IngestMediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestMedia {
    if (json == null) {
        return json;
    }
    return {
        
        'caption': json['caption'] === undefined ? undefined : json['caption'] === null ? null : json['caption'],
        'collectionId': json['collection_id'] === undefined ? undefined : json['collection_id'] === null ? null : json['collection_id'],
        'customerId': json['customer_id'] === undefined ? undefined : json['customer_id'] === null ? null : json['customer_id'],
        'data': json['data'] === undefined ? undefined : json['data'] === null ? null : json['data'],
        'filename': json['filename'] === undefined ? undefined : json['filename'] === null ? null : json['filename'],
        'metadata': json['metadata'] === undefined ? undefined : json['metadata'] === null ? null : json['metadata'],
        'parentRef': json['parent_ref'] === undefined ? undefined : json['parent_ref'] === null ? null : json['parent_ref'],
        'stripExif': json['strip_exif'] == null ? undefined : json['strip_exif'],
        'tags': json['tags'] === undefined ? undefined : json['tags'] === null ? null : json['tags'],
        'url': json['url'] === undefined ? undefined : json['url'] === null ? null : json['url'],
    };
}

export function IngestMediaToJSON(json: any): IngestMedia {
    return IngestMediaToJSONTyped(json, false);
}

export function IngestMediaToJSONTyped(value?: IngestMedia | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'caption': value['caption'],
        'collection_id': value['collectionId'],
        'customer_id': value['customerId'],
        'data': value['data'],
        'filename': value['filename'],
        'metadata': value['metadata'],
        'parent_ref': value['parentRef'],
        'strip_exif': value['stripExif'],
        'tags': value['tags'],
        'url': value['url'],
    };
}

