/* tslint:disable */
/* eslint-disable */
/**
 * FEVER Retrieval
 * The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * 
     */
    done?: number;
    /**
     * 
     */
    error?: string | null;
    /**
     * 
     */
    id: number;
    /**
     * Items skipped by delta ingest because their content was already indexed (overwrite=false).
     */
    skipped?: number;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    total?: number;
}

/**
 * Check if a given object implements the Job interface.
 */
export function instanceOfJob(value: object): value is Job {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function JobFromJSON(json: any): Job {
    return JobFromJSONTyped(json, false);
}

export function JobFromJSONTyped(json: any, ignoreDiscriminator: boolean): Job {
    if (json == null) {
        return json;
    }
    return {
        
        'done': json['done'] == null ? undefined : json['done'],
        'error': json['error'] === undefined ? undefined : json['error'] === null ? null : json['error'],
        'id': json['id'],
        'skipped': json['skipped'] == null ? undefined : json['skipped'],
        'status': json['status'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function JobToJSON(json: any): Job {
    return JobToJSONTyped(json, false);
}

export function JobToJSONTyped(value?: Job | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'done': value['done'],
        'error': value['error'],
        'id': value['id'],
        'skipped': value['skipped'],
        'status': value['status'],
        'total': value['total'],
    };
}

