/*
 * FEVER Retrieval
 *
 * The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LowdownLabs.Fever.Client.FileParameter;
using OpenAPIDateConverter = LowdownLabs.Fever.Client.OpenAPIDateConverter;

namespace LowdownLabs.Fever.Model
{
    /// <summary>
    /// DuplicatesRequest
    /// </summary>
    [DataContract(Name = "DuplicatesRequest")]
    public partial class DuplicatesRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DuplicatesRequest" /> class.
        /// </summary>
        /// <param name="customerId">Restrict the scan to media tagged with this customer_id. A scoped key is always forced to its own customer_id; an admin key may pass any customer_id or none (all customers)..</param>
        /// <param name="customerIds">Admin only: restrict the scan to this set of customers. Spanning more than one customer is how cross-account duplicates (the same item submitted under different accounts) are found. Ignored for scoped keys, which stay pinned..</param>
        /// <param name="limit">Max items to scan for near-duplicates. (default to 500).</param>
        /// <param name="threshold">Similarity cutoff 0..1; higher is stricter (1.0 &#x3D; near-identical). (default to 0.92M).</param>
        public DuplicatesRequest(string customerId = default, List<string> customerIds = default, int limit = 500, decimal threshold = 0.92M)
        {
            this.CustomerId = customerId;
            this.CustomerIds = customerIds;
            this.Limit = limit;
            this.Threshold = threshold;
        }

        /// <summary>
        /// Restrict the scan to media tagged with this customer_id. A scoped key is always forced to its own customer_id; an admin key may pass any customer_id or none (all customers).
        /// </summary>
        /// <value>Restrict the scan to media tagged with this customer_id. A scoped key is always forced to its own customer_id; an admin key may pass any customer_id or none (all customers).</value>
        [DataMember(Name = "customer_id", EmitDefaultValue = true)]
        public string CustomerId { get; set; }

        /// <summary>
        /// Admin only: restrict the scan to this set of customers. Spanning more than one customer is how cross-account duplicates (the same item submitted under different accounts) are found. Ignored for scoped keys, which stay pinned.
        /// </summary>
        /// <value>Admin only: restrict the scan to this set of customers. Spanning more than one customer is how cross-account duplicates (the same item submitted under different accounts) are found. Ignored for scoped keys, which stay pinned.</value>
        [DataMember(Name = "customer_ids", EmitDefaultValue = true)]
        public List<string> CustomerIds { get; set; }

        /// <summary>
        /// Max items to scan for near-duplicates.
        /// </summary>
        /// <value>Max items to scan for near-duplicates.</value>
        [DataMember(Name = "limit", EmitDefaultValue = false)]
        public int Limit { get; set; }

        /// <summary>
        /// Similarity cutoff 0..1; higher is stricter (1.0 &#x3D; near-identical).
        /// </summary>
        /// <value>Similarity cutoff 0..1; higher is stricter (1.0 &#x3D; near-identical).</value>
        [DataMember(Name = "threshold", EmitDefaultValue = false)]
        public decimal Threshold { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DuplicatesRequest {\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  CustomerIds: ").Append(CustomerIds).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Threshold: ").Append(Threshold).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Limit (int) maximum
            if (this.Limit > (int)5000)
            {
                yield return new ValidationResult("Invalid value for Limit, must be a value less than or equal to 5000.", new [] { "Limit" });
            }

            // Limit (int) minimum
            if (this.Limit < (int)1)
            {
                yield return new ValidationResult("Invalid value for Limit, must be a value greater than or equal to 1.", new [] { "Limit" });
            }

            // Threshold (decimal) maximum
            if (this.Threshold > (decimal)1.0)
            {
                yield return new ValidationResult("Invalid value for Threshold, must be a value less than or equal to 1.0.", new [] { "Threshold" });
            }

            // Threshold (decimal) minimum
            if (this.Threshold < (decimal)0.0)
            {
                yield return new ValidationResult("Invalid value for Threshold, must be a value greater than or equal to 0.0.", new [] { "Threshold" });
            }

            yield break;
        }
    }

}
