/*
 * FEVER Retrieval
 *
 * The multimodal media database. Images, video, audio, office documents, and LiDAR in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans, collection grouping, and asset-to-asset attachments. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.4.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = LowdownLabs.Fever.Client.FileParameter;
using OpenAPIDateConverter = LowdownLabs.Fever.Client.OpenAPIDateConverter;

namespace LowdownLabs.Fever.Model
{
    /// <summary>
    /// IngestMedia
    /// </summary>
    [DataContract(Name = "IngestMedia")]
    public partial class IngestMedia : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IngestMedia" /> class.
        /// </summary>
        /// <param name="caption">Optional caption/keywords; indexed at the highest text-search weight..</param>
        /// <param name="collectionId">Optional grouping you own (project, case, site - FEVER stores and filters it, never interprets it). Filterable at search time; returned on hits..</param>
        /// <param name="customerId">Optional tag attributing this item to one of your customers; filterable at search time..</param>
        /// <param name="data">Base64-encoded media item bytes..</param>
        /// <param name="filename">Original file name. Drives format detection for inline documents and LiDAR (extensions like .csv or .las - office formats are recognized by their bytes alone) and is stored on the blob for media info and attachment listings..</param>
        /// <param name="metadata">Opaque JSON returned with search hits..</param>
        /// <param name="parentRef">Optional pointer to a related parent asset (its external_ref, key, or blob_id). Non-searchable companions such as LiDAR scans declare the photo or video they belong to; the parent&#39;s record lists them back as attachments..</param>
        /// <param name="stripExif">Skip EXIF extraction/retention for this item. (default to false).</param>
        /// <param name="tags">Optional tags for this item; indexed for text search and returned on hits. Merged with the appliance&#39;s zero-shot autotags..</param>
        /// <param name="url">An s3:// URI to one media item you already store, instead of inline bytes..</param>
        public IngestMedia(string caption = default, string collectionId = default, string customerId = default, string data = default, string filename = default, Dictionary<string, Object> metadata = default, string parentRef = default, bool stripExif = false, List<string> tags = default, string url = default)
        {
            this.Caption = caption;
            this.CollectionId = collectionId;
            this.CustomerId = customerId;
            this.Data = data;
            this.Filename = filename;
            this.Metadata = metadata;
            this.ParentRef = parentRef;
            this.StripExif = stripExif;
            this.Tags = tags;
            this.Url = url;
        }

        /// <summary>
        /// Optional caption/keywords; indexed at the highest text-search weight.
        /// </summary>
        /// <value>Optional caption/keywords; indexed at the highest text-search weight.</value>
        [DataMember(Name = "caption", EmitDefaultValue = true)]
        public string Caption { get; set; }

        /// <summary>
        /// Optional grouping you own (project, case, site - FEVER stores and filters it, never interprets it). Filterable at search time; returned on hits.
        /// </summary>
        /// <value>Optional grouping you own (project, case, site - FEVER stores and filters it, never interprets it). Filterable at search time; returned on hits.</value>
        [DataMember(Name = "collection_id", EmitDefaultValue = true)]
        public string CollectionId { get; set; }

        /// <summary>
        /// Optional tag attributing this item to one of your customers; filterable at search time.
        /// </summary>
        /// <value>Optional tag attributing this item to one of your customers; filterable at search time.</value>
        [DataMember(Name = "customer_id", EmitDefaultValue = true)]
        public string CustomerId { get; set; }

        /// <summary>
        /// Base64-encoded media item bytes.
        /// </summary>
        /// <value>Base64-encoded media item bytes.</value>
        [DataMember(Name = "data", EmitDefaultValue = true)]
        public string Data { get; set; }

        /// <summary>
        /// Original file name. Drives format detection for inline documents and LiDAR (extensions like .csv or .las - office formats are recognized by their bytes alone) and is stored on the blob for media info and attachment listings.
        /// </summary>
        /// <value>Original file name. Drives format detection for inline documents and LiDAR (extensions like .csv or .las - office formats are recognized by their bytes alone) and is stored on the blob for media info and attachment listings.</value>
        [DataMember(Name = "filename", EmitDefaultValue = true)]
        public string Filename { get; set; }

        /// <summary>
        /// Opaque JSON returned with search hits.
        /// </summary>
        /// <value>Opaque JSON returned with search hits.</value>
        [DataMember(Name = "metadata", EmitDefaultValue = true)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Optional pointer to a related parent asset (its external_ref, key, or blob_id). Non-searchable companions such as LiDAR scans declare the photo or video they belong to; the parent&#39;s record lists them back as attachments.
        /// </summary>
        /// <value>Optional pointer to a related parent asset (its external_ref, key, or blob_id). Non-searchable companions such as LiDAR scans declare the photo or video they belong to; the parent&#39;s record lists them back as attachments.</value>
        [DataMember(Name = "parent_ref", EmitDefaultValue = true)]
        public string ParentRef { get; set; }

        /// <summary>
        /// Skip EXIF extraction/retention for this item.
        /// </summary>
        /// <value>Skip EXIF extraction/retention for this item.</value>
        [DataMember(Name = "strip_exif", EmitDefaultValue = true)]
        public bool StripExif { get; set; }

        /// <summary>
        /// Optional tags for this item; indexed for text search and returned on hits. Merged with the appliance&#39;s zero-shot autotags.
        /// </summary>
        /// <value>Optional tags for this item; indexed for text search and returned on hits. Merged with the appliance&#39;s zero-shot autotags.</value>
        [DataMember(Name = "tags", EmitDefaultValue = true)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// An s3:// URI to one media item you already store, instead of inline bytes.
        /// </summary>
        /// <value>An s3:// URI to one media item you already store, instead of inline bytes.</value>
        [DataMember(Name = "url", EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IngestMedia {\n");
            sb.Append("  Caption: ").Append(Caption).Append("\n");
            sb.Append("  CollectionId: ").Append(CollectionId).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  ParentRef: ").Append(ParentRef).Append("\n");
            sb.Append("  StripExif: ").Append(StripExif).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
