<?php
/**
 * SearchHit
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LowdownLabs\Fever
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FEVER Retrieval
 *
 * The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LowdownLabs\Fever\Model;

use \ArrayAccess;
use \LowdownLabs\Fever\ObjectSerializer;

/**
 * SearchHit Class Doc Comment
 *
 * @category Class
 * @package  LowdownLabs\Fever
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SearchHit implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'SearchHit';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'blob_id' => 'int',
        'caption' => 'string',
        'customer_id' => 'string',
        'duplicate_count' => 'int',
        'duplicates' => 'int[]',
        'geo_label' => 'string',
        'headline' => 'string',
        'height' => 'int',
        'kind' => 'string',
        'media_ref' => 'string',
        'metadata' => 'array<string,mixed>',
        'score' => 'float',
        'score_type' => 'string',
        'seek_ms' => 'int',
        'span' => '\LowdownLabs\Fever\Model\MediaSpan',
        'span_headline' => 'string',
        'tags' => 'string[]',
        'width' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'blob_id' => null,
        'caption' => null,
        'customer_id' => null,
        'duplicate_count' => null,
        'duplicates' => null,
        'geo_label' => null,
        'headline' => null,
        'height' => null,
        'kind' => null,
        'media_ref' => null,
        'metadata' => null,
        'score' => null,
        'score_type' => null,
        'seek_ms' => null,
        'span' => null,
        'span_headline' => null,
        'tags' => null,
        'width' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'blob_id' => false,
        'caption' => true,
        'customer_id' => true,
        'duplicate_count' => false,
        'duplicates' => false,
        'geo_label' => true,
        'headline' => true,
        'height' => true,
        'kind' => true,
        'media_ref' => true,
        'metadata' => true,
        'score' => false,
        'score_type' => false,
        'seek_ms' => true,
        'span' => true,
        'span_headline' => true,
        'tags' => false,
        'width' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'blob_id' => 'blob_id',
        'caption' => 'caption',
        'customer_id' => 'customer_id',
        'duplicate_count' => 'duplicate_count',
        'duplicates' => 'duplicates',
        'geo_label' => 'geo_label',
        'headline' => 'headline',
        'height' => 'height',
        'kind' => 'kind',
        'media_ref' => 'media_ref',
        'metadata' => 'metadata',
        'score' => 'score',
        'score_type' => 'score_type',
        'seek_ms' => 'seek_ms',
        'span' => 'span',
        'span_headline' => 'span_headline',
        'tags' => 'tags',
        'width' => 'width'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'blob_id' => 'setBlobId',
        'caption' => 'setCaption',
        'customer_id' => 'setCustomerId',
        'duplicate_count' => 'setDuplicateCount',
        'duplicates' => 'setDuplicates',
        'geo_label' => 'setGeoLabel',
        'headline' => 'setHeadline',
        'height' => 'setHeight',
        'kind' => 'setKind',
        'media_ref' => 'setMediaRef',
        'metadata' => 'setMetadata',
        'score' => 'setScore',
        'score_type' => 'setScoreType',
        'seek_ms' => 'setSeekMs',
        'span' => 'setSpan',
        'span_headline' => 'setSpanHeadline',
        'tags' => 'setTags',
        'width' => 'setWidth'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'blob_id' => 'getBlobId',
        'caption' => 'getCaption',
        'customer_id' => 'getCustomerId',
        'duplicate_count' => 'getDuplicateCount',
        'duplicates' => 'getDuplicates',
        'geo_label' => 'getGeoLabel',
        'headline' => 'getHeadline',
        'height' => 'getHeight',
        'kind' => 'getKind',
        'media_ref' => 'getMediaRef',
        'metadata' => 'getMetadata',
        'score' => 'getScore',
        'score_type' => 'getScoreType',
        'seek_ms' => 'getSeekMs',
        'span' => 'getSpan',
        'span_headline' => 'getSpanHeadline',
        'tags' => 'getTags',
        'width' => 'getWidth'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const KIND_IMAGE = 'image';
    public const KIND_VIDEO = 'video';
    public const KIND_AUDIO = 'audio';
    public const KIND_PDF = 'pdf';
    public const KIND_DOC = 'doc';
    public const KIND_NOTE = 'note';
    public const SCORE_TYPE_COSINE = 'cosine';
    public const SCORE_TYPE_COSINELEX = 'cosine+lex';
    public const SCORE_TYPE_RRF = 'rrf';
    public const SCORE_TYPE_RERANK = 'rerank';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getKindAllowableValues()
    {
        return [
            self::KIND_IMAGE,
            self::KIND_VIDEO,
            self::KIND_AUDIO,
            self::KIND_PDF,
            self::KIND_DOC,
            self::KIND_NOTE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getScoreTypeAllowableValues()
    {
        return [
            self::SCORE_TYPE_COSINE,
            self::SCORE_TYPE_COSINELEX,
            self::SCORE_TYPE_RRF,
            self::SCORE_TYPE_RERANK,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('blob_id', $data ?? [], null);
        $this->setIfExists('caption', $data ?? [], null);
        $this->setIfExists('customer_id', $data ?? [], null);
        $this->setIfExists('duplicate_count', $data ?? [], 0);
        $this->setIfExists('duplicates', $data ?? [], null);
        $this->setIfExists('geo_label', $data ?? [], null);
        $this->setIfExists('headline', $data ?? [], null);
        $this->setIfExists('height', $data ?? [], null);
        $this->setIfExists('kind', $data ?? [], null);
        $this->setIfExists('media_ref', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('score', $data ?? [], null);
        $this->setIfExists('score_type', $data ?? [], null);
        $this->setIfExists('seek_ms', $data ?? [], null);
        $this->setIfExists('span', $data ?? [], null);
        $this->setIfExists('span_headline', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('width', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['blob_id'] === null) {
            $invalidProperties[] = "'blob_id' can't be null";
        }
        $allowedValues = $this->getKindAllowableValues();
        if (!is_null($this->container['kind']) && !in_array($this->container['kind'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'kind', must be one of '%s'",
                $this->container['kind'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['score'] === null) {
            $invalidProperties[] = "'score' can't be null";
        }
        if ($this->container['score_type'] === null) {
            $invalidProperties[] = "'score_type' can't be null";
        }
        $allowedValues = $this->getScoreTypeAllowableValues();
        if (!is_null($this->container['score_type']) && !in_array($this->container['score_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'score_type', must be one of '%s'",
                $this->container['score_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets blob_id
     *
     * @return int
     */
    public function getBlobId()
    {
        return $this->container['blob_id'];
    }

    /**
     * Sets blob_id
     *
     * @param int $blob_id blob_id
     *
     * @return self
     */
    public function setBlobId($blob_id)
    {
        if (is_null($blob_id)) {
            throw new \InvalidArgumentException('non-nullable blob_id cannot be null');
        }
        $this->container['blob_id'] = $blob_id;

        return $this;
    }

    /**
     * Gets caption
     *
     * @return string|null
     */
    public function getCaption()
    {
        return $this->container['caption'];
    }

    /**
     * Sets caption
     *
     * @param string|null $caption caption
     *
     * @return self
     */
    public function setCaption($caption)
    {
        if (is_null($caption)) {
            array_push($this->openAPINullablesSetToNull, 'caption');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('caption', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['caption'] = $caption;

        return $this;
    }

    /**
     * Gets customer_id
     *
     * @return string|null
     */
    public function getCustomerId()
    {
        return $this->container['customer_id'];
    }

    /**
     * Sets customer_id
     *
     * @param string|null $customer_id customer_id
     *
     * @return self
     */
    public function setCustomerId($customer_id)
    {
        if (is_null($customer_id)) {
            array_push($this->openAPINullablesSetToNull, 'customer_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('customer_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['customer_id'] = $customer_id;

        return $this;
    }

    /**
     * Gets duplicate_count
     *
     * @return int|null
     */
    public function getDuplicateCount()
    {
        return $this->container['duplicate_count'];
    }

    /**
     * Sets duplicate_count
     *
     * @param int|null $duplicate_count Number of near-duplicates collapsed into this hit.
     *
     * @return self
     */
    public function setDuplicateCount($duplicate_count)
    {
        if (is_null($duplicate_count)) {
            throw new \InvalidArgumentException('non-nullable duplicate_count cannot be null');
        }
        $this->container['duplicate_count'] = $duplicate_count;

        return $this;
    }

    /**
     * Gets duplicates
     *
     * @return int[]|null
     */
    public function getDuplicates()
    {
        return $this->container['duplicates'];
    }

    /**
     * Sets duplicates
     *
     * @param int[]|null $duplicates blob_ids of near-duplicates collapsed into this hit.
     *
     * @return self
     */
    public function setDuplicates($duplicates)
    {
        if (is_null($duplicates)) {
            throw new \InvalidArgumentException('non-nullable duplicates cannot be null');
        }
        $this->container['duplicates'] = $duplicates;

        return $this;
    }

    /**
     * Gets geo_label
     *
     * @return string|null
     */
    public function getGeoLabel()
    {
        return $this->container['geo_label'];
    }

    /**
     * Sets geo_label
     *
     * @param string|null $geo_label Reverse-geocode label from EXIF GPS (e.g. 'Lisbon, PT'), when the asset carries intact camera coordinates (the geo:<label> tag rides alongside).
     *
     * @return self
     */
    public function setGeoLabel($geo_label)
    {
        if (is_null($geo_label)) {
            array_push($this->openAPINullablesSetToNull, 'geo_label');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('geo_label', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['geo_label'] = $geo_label;

        return $this;
    }

    /**
     * Gets headline
     *
     * @return string|null
     */
    public function getHeadline()
    {
        return $this->container['headline'];
    }

    /**
     * Sets headline
     *
     * @param string|null $headline Lexical FTS highlight (ts_headline) when the hit came via full-text search.
     *
     * @return self
     */
    public function setHeadline($headline)
    {
        if (is_null($headline)) {
            array_push($this->openAPINullablesSetToNull, 'headline');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('headline', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['headline'] = $headline;

        return $this;
    }

    /**
     * Gets height
     *
     * @return int|null
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param int|null $height Stored media height in pixels, when known.
     *
     * @return self
     */
    public function setHeight($height)
    {
        if (is_null($height)) {
            array_push($this->openAPINullablesSetToNull, 'height');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('height', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets kind
     *
     * @return string|null
     */
    public function getKind()
    {
        return $this->container['kind'];
    }

    /**
     * Sets kind
     *
     * @param string|null $kind Media kind of this hit's parent blob.
     *
     * @return self
     */
    public function setKind($kind)
    {
        if (is_null($kind)) {
            array_push($this->openAPINullablesSetToNull, 'kind');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('kind', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getKindAllowableValues();
        if (!is_null($kind) && !in_array($kind, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'kind', must be one of '%s'",
                    $kind,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['kind'] = $kind;

        return $this;
    }

    /**
     * Gets media_ref
     *
     * @return string|null
     */
    public function getMediaRef()
    {
        return $this->container['media_ref'];
    }

    /**
     * Sets media_ref
     *
     * @param string|null $media_ref s3:// URI of the matched media item.
     *
     * @return self
     */
    public function setMediaRef($media_ref)
    {
        if (is_null($media_ref)) {
            array_push($this->openAPINullablesSetToNull, 'media_ref');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('media_ref', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['media_ref'] = $media_ref;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,mixed>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,mixed>|null $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            array_push($this->openAPINullablesSetToNull, 'metadata');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('metadata', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets score
     *
     * @return float
     */
    public function getScore()
    {
        return $this->container['score'];
    }

    /**
     * Sets score
     *
     * @param float $score For score_type 'rerank' this is the model's match probability in [0,1] (a calibrated confidence); 'cosine' is vector similarity; 'rrf' is a lexical rank score.
     *
     * @return self
     */
    public function setScore($score)
    {
        if (is_null($score)) {
            throw new \InvalidArgumentException('non-nullable score cannot be null');
        }
        $this->container['score'] = $score;

        return $this;
    }

    /**
     * Gets score_type
     *
     * @return string
     */
    public function getScoreType()
    {
        return $this->container['score_type'];
    }

    /**
     * Sets score_type
     *
     * @param string $score_type score_type
     *
     * @return self
     */
    public function setScoreType($score_type)
    {
        if (is_null($score_type)) {
            throw new \InvalidArgumentException('non-nullable score_type cannot be null');
        }
        $allowedValues = $this->getScoreTypeAllowableValues();
        if (!in_array($score_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'score_type', must be one of '%s'",
                    $score_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['score_type'] = $score_type;

        return $this;
    }

    /**
     * Gets seek_ms
     *
     * @return int|null
     */
    public function getSeekMs()
    {
        return $this->container['seek_ms'];
    }

    /**
     * Sets seek_ms
     *
     * @param int|null $seek_ms For video hits: timestamp of the winning frame, for seek-to-moment playback.
     *
     * @return self
     */
    public function setSeekMs($seek_ms)
    {
        if (is_null($seek_ms)) {
            array_push($this->openAPINullablesSetToNull, 'seek_ms');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('seek_ms', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['seek_ms'] = $seek_ms;

        return $this;
    }

    /**
     * Gets span
     *
     * @return \LowdownLabs\Fever\Model\MediaSpan|null
     */
    public function getSpan()
    {
        return $this->container['span'];
    }

    /**
     * Sets span
     *
     * @param \LowdownLabs\Fever\Model\MediaSpan|null $span For transcript hits: the matching whisper segment, with literal text for highlighting.
     *
     * @return self
     */
    public function setSpan($span)
    {
        if (is_null($span)) {
            array_push($this->openAPINullablesSetToNull, 'span');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('span', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['span'] = $span;

        return $this;
    }

    /**
     * Gets span_headline
     *
     * @return string|null
     */
    public function getSpanHeadline()
    {
        return $this->container['span_headline'];
    }

    /**
     * Sets span_headline
     *
     * @param string|null $span_headline Lexical FTS highlight (ts_headline) of the winning transcript segment.
     *
     * @return self
     */
    public function setSpanHeadline($span_headline)
    {
        if (is_null($span_headline)) {
            array_push($this->openAPINullablesSetToNull, 'span_headline');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('span_headline', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['span_headline'] = $span_headline;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags Tags on this item: client-supplied at ingest and/or the appliance's zero-shot autotags.
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets width
     *
     * @return int|null
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param int|null $width Stored media width in pixels, when known.
     *
     * @return self
     */
    public function setWidth($width)
    {
        if (is_null($width)) {
            array_push($this->openAPINullablesSetToNull, 'width');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('width', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['width'] = $width;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


