/*
 * FEVER Retrieval
 *
 * The multimodal media database. Images, video, audio, office documents, and LiDAR in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans, collection grouping, and asset-to-asset attachments. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.4.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LowdownLabs.Fever.Model;
using LowdownLabs.Fever.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LowdownLabs.Fever.Test.Model
{
    /// <summary>
    ///  Class for testing DuplicatesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DuplicatesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DuplicatesResponse
        //private DuplicatesResponse instance;

        public DuplicatesResponseTests()
        {
            // TODO uncomment below to create an instance of DuplicatesResponse
            //instance = new DuplicatesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DuplicatesResponse
        /// </summary>
        [Fact]
        public void DuplicatesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DuplicatesResponse
            //Assert.IsType<DuplicatesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Clusters'
        /// </summary>
        [Fact]
        public void ClustersTest()
        {
            // TODO unit test for the property 'Clusters'
        }

        /// <summary>
        /// Test the property 'DuplicateClusters'
        /// </summary>
        [Fact]
        public void DuplicateClustersTest()
        {
            // TODO unit test for the property 'DuplicateClusters'
        }

        /// <summary>
        /// Test the property 'TotalDuplicates'
        /// </summary>
        [Fact]
        public void TotalDuplicatesTest()
        {
            // TODO unit test for the property 'TotalDuplicates'
        }
    }
}
