/*
 * FEVER Retrieval
 *
 * The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LowdownLabs.Fever.Model;
using LowdownLabs.Fever.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LowdownLabs.Fever.Test.Model
{
    /// <summary>
    ///  Class for testing HTTPValidationError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HTTPValidationErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HTTPValidationError
        //private HTTPValidationError instance;

        public HTTPValidationErrorTests()
        {
            // TODO uncomment below to create an instance of HTTPValidationError
            //instance = new HTTPValidationError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HTTPValidationError
        /// </summary>
        [Fact]
        public void HTTPValidationErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" HTTPValidationError
            //Assert.IsType<HTTPValidationError>(instance);
        }

        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }
    }
}
