/*
 * FEVER Retrieval
 *
 * The multimodal media database. Images, video, and audio in one table: hybrid vector + full-text search, dedupe, seek-to-moment video hits, whisper transcript spans. Tenancy, scale, and isolation are automatic; the tenant is taken from the API key.
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LowdownLabs.Fever.Model;
using LowdownLabs.Fever.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LowdownLabs.Fever.Test.Model
{
    /// <summary>
    ///  Class for testing IngestRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IngestRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IngestRequest
        //private IngestRequest instance;

        public IngestRequestTests()
        {
            // TODO uncomment below to create an instance of IngestRequest
            //instance = new IngestRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IngestRequest
        /// </summary>
        [Fact]
        public void IngestRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IngestRequest
            //Assert.IsType<IngestRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Media'
        /// </summary>
        [Fact]
        public void MediaTest()
        {
            // TODO unit test for the property 'Media'
        }

        /// <summary>
        /// Test the property 'Overwrite'
        /// </summary>
        [Fact]
        public void OverwriteTest()
        {
            // TODO unit test for the property 'Overwrite'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'TargetRes'
        /// </summary>
        [Fact]
        public void TargetResTest()
        {
            // TODO unit test for the property 'TargetRes'
        }
    }
}
